### ISSUE TITLE
dynamic surroundings hell tempest doesn't work anymore

### ISSUE THREAD

**Issue by 0Navis0** [LogicTechCorp/NetherEx-Archive#10]
The hell tempest added by the mod Dynamic Surroundings when it rains (kind of rain equivalent in the nether) doesn't work more.

**Comment by 0Navis0** [comment]
An another error I noticed is when it is the rain weather, that I quit Minecraft on the hell and lauch again the game still in the hell, it rains in the hell. And change the weather to clear doesn't change aynthing. I have to leave the hell and come back inside for it stops to rain.

**Comment by LogicTechCorp** [comment]
I'm going to link in @Abastro to see what we can do?

**Comment by LogicTechCorp** [comment]
Closed as this issue is on Dynamic surroundings end.
https://minecraft.curseforge.com/projects/dynamic-surroundings-unofficial/issues/2
