### ISSUE TITLE
Orange Salamander Hide armor recipes broken

### ISSUE THREAD

**Issue by angelnc1989** [LogicTechCorp/NetherEx-Archive#100]
The recipes for Orange Salamander Hide armor use Wither Bones instead of Orange Salamander Hide.
![image](https://user-images.githubusercontent.com/5382585/43187716-83ef28b6-8ff2-11e8-8853-95459957feb6.png)

**Comment by LogicTechCorp** [comment]
This has been fixed in the latest version.
