### ISSUE TITLE
Crash when starting the game

### ISSUE THREAD

**Issue by angelnc1989** [LogicTechCorp/NetherEx-Archive#104]
https://pastebin.com/x1fWShDa

Just updated to the latest version and the game crashes on startup.

**Comment by LogicTechCorp** [comment]
Get the latest version of LibEx.

**Comment by angelnc1989** [comment]
My bad.

**Comment by LogicTechCorp** [comment]
Yeah, I forgot to update the version of LEX required so it doesn't tell you that you need the new one.

**Comment by angelnc1989** [comment]
Curseforge "Last Updated" filter is kind of slow to update too, so I didn't realize LibEx was updated.

**Comment by LogicTechCorp** [comment]
Ah, okay.
