### ISSUE TITLE
[1.12.2]Crash when entering Nether

### ISSUE THREAD

**Issue by SassyCultist** [LogicTechCorp/NetherEx-Archive#105]
[crash-2018-07-25_17.25.01-server.txt](https://github.com/MineEx/NetherEx/files/2229601/crash-2018-07-25_17.25.01-server.txt)

Minecraft Forge: 14.23.4.2739
NetherEx: 2.0.2
LibEx: 1.0.2

**Comment by LogicTechCorp** [comment]
Try deleting the NetherEx config folder.

**Comment by SassyCultist** [comment]
That did not fix the issue.

**Comment by LogicTechCorp** [comment]
If you run just LEX and NEX does it still happen? I just downloaded the latest versions to test and I don't crash.

**Comment by SassyCultist** [comment]
It does not crash with just these mods.

**Comment by LogicTechCorp** [comment]
Then it must be a mod conflict. Are you using any mods that change entity spawning or world generation?

**Comment by SassyCultist** [comment]
I will attach a modlist. 
[list.txt](https://github.com/MineEx/NetherEx/files/2229871/list.txt)

**Comment by SassyCultist** [comment]
I had nothing built in the nether so I regenerated the dimension and everything seems to be fine.

**Comment by kreezxil** [comment]
I was fine before I updated your mod in my pack today. World of Dragons. Prior to this your mod did not crash my pack. I know you want to say it is a mod conflict but can you please just fix your mod so it doesn't do it. It's reporting an NPE.

Server Crash Reports
http://paste.ubuntu.com/p/bYNCtCBVyB/
http://paste.ubuntu.com/p/pxqnc3XKHT/
http://paste.ubuntu.com/p/HJJXn8WYMW/
http://paste.ubuntu.com/p/ntpThfgcpN/
http://paste.ubuntu.com/p/Cwg3XZSHVB/
http://paste.ubuntu.com/p/jR373KW3Xq/

On line https://github.com/MineEx/NetherEx/blob/1.12.x/src/main/java/nex/world/gen/ChunkGeneratorNether.java#L445 I believe you need to make a check to see if the list being returned is null and if it is simply return an empty list.

**Comment by LogicTechCorp** [comment]
This issue has been fixed in the latest release. Be sure to grab both LEX and NEX.
