### ISSUE TITLE
warning about the Biomes O Plenty nether biomes, plants and mobs

### ISSUE THREAD

**Issue by 0Navis0** [LogicTechCorp/NetherEx-Archive#11]
I just create this issue for warning that Biomes O Plenty will soon reintegrate the nether biomes, plants and mobs. So you will have to make it compatible with your mod.

**Comment by LogicTechCorp** [comment]
Yes, I am already aware of this. Thank you for all of the help with NetherEx.

**Comment by 0Navis0** [comment]
You're welcome, I'm so happy that someone brings back nether expansion. I try to help this mod as I can. :)
