### ISSUE TITLE
[Config Suggestion] Nether Generation Configuration

### ISSUE THREAD

**Issue by UnlimatedStone9** [LogicTechCorp/NetherEx-Archive#113]
Implementing a config to prevent NetherEx from overwriting the nether would be extremely useful for Modpacks that would like to have the features from the mod like wither bones and unique netherrack types but would rather have a different mod handling how the nether generates
 (Like how YUNoMakeGoodMap converts the nether into a void)

This would be especially useful for SkyBlock Modpacks as the nether generates when its not wanted

**Comment by LogicTechCorp** [comment]
A config option has been added in the latest version.
