### ISSUE TITLE
Lag from file access in onWorldTick

### ISSUE THREAD

**Issue by LemADEC** [LogicTechCorp/NetherEx-Archive#115]
As of NetherEx-1.12.2-2.0.6, file access are observed in onWorldTick.
File access is fairly slow operation, consider using a cache or a multithreaded approach instead:
![image](https://user-images.githubusercontent.com/4776032/44207362-364f5780-a15d-11e8-95e7-9f1a7f07fd34.png)

**Comment by LogicTechCorp** [comment]
I'm not too sure on what I could do. The Pigtificate Village data is already saved in a cache in the World object. Do you know of another mod that includes their own villages that I could take a look at?

**Comment by LemADEC** [comment]
Maybe you can cache the result from MapStorage.loadData() instead of calling it each time?
You'll have to grab the world unloading event to clear your cache.
Not sure what you've in there, but remember to keep only WeakReferences to world and entity objects.

**Comment by LogicTechCorp** [comment]
This is probably what I am going to do:

World Handler
```
@Mod.EventBusSubscriber(modid = NetherEx.MOD_ID)
public class WorldHandler
{
    @SubscribeEvent
    public static void onWorldLoad(WorldEvent.Load event)
    {
        World world = event.getWorld();

        if(!world.isRemote)
        {
            PigtificateVillageManager.loadVillageData(event.getWorld());
        }
    }

    @SubscribeEvent
    public static void onWorldTick(TickEvent.WorldTickEvent event)
    {
        World world = event.world;

        if(event.phase == TickEvent.Phase.START)
        {
            if(!world.isRemote)
            {
                if(PigtificateVillageManager.hasData(world))
                {
                    PigtificateVillageData data = PigtificateVillageManager.getVillageData(world, false);

                    if(data != null)
                    {
                        data.tick();
                    }
                }
            }
        }
    }

    @SubscribeEvent
    public static void onWorldUnload(WorldEvent.Unload event)
    {
        World world = event.getWorld();

        if(!world.isRemote)
        {
            PigtificateVillageManager.unloadVillageData(world);
        }
    }
}
```

Pigtificate Village Manager
```
public class PigtificateVillageManager
{
    private static final Map<Integer, PigtificateVillageData> PIGTIFICATE_VILLAGE_DATA = new HashMap<>();

    public static void loadVillageData(World world)
    {
        if(!hasData(world))
        {
            getVillageData(world, false);
        }
    }

    public static void unloadVillageData(World world)
    {
        PIGTIFICATE_VILLAGE_DATA.remove(world.provider.getDimension());
    }

    public static boolean hasData(World world)
    {
        return PIGTIFICATE_VILLAGE_DATA.containsKey(world.provider.getDimension());
    }

    public static PigtificateVillageData getVillageData(World world, boolean createData)
    {
        PigtificateVillageData data;
        int dimensionId = world.provider.getDimension();

        if(hasData(world))
        {
            data = PIGTIFICATE_VILLAGE_DATA.get(dimensionId);
        }
        else
        {
            String worldFile = PigtificateVillageData.getFileName(world);
            data = (PigtificateVillageData) world.getPerWorldStorage().getOrLoadData(PigtificateVillageData.class, worldFile);

            if(data == null && createData)
            {
                data = new PigtificateVillageData(world);
                world.getPerWorldStorage().setData(worldFile, data);
            }
        }

        if(data != null)
        {
            data.setWorld(world);
            PIGTIFICATE_VILLAGE_DATA.put(dimensionId, data);
        }

        return data;
    }
}
```

Do you have any thoughts?

**Comment by LemADEC** [comment]
Nice! it's a good idea indeed to draft your design before jumping into implementation :)

In onWorldLoad(), you can reuse your world local variable.

Try to prefer late allocation: in `onWorldTick()`, move `World world = event.world;` inside the first if.

When calling `hasDate() > containsKey()`, you are already doing a lookup, that will be done again with `getVillageData() > get()`. It won't change much here with this small collection, but it's a good habit to address this.

To be on the safe side, you want to use a WeakReference to the world in https://github.com/MineEx/NetherEx/blob/1.12.x/src/main/java/nex/village/PigtificateVillage.java#L43
Or even better, don't store it at all, pass it in argument when needed, just checking that the dimension id is the same.

On a side note, try to restrict creating lots of temporary objects as this will cause GC lag. For example, in https://github.com/MineEx/NetherEx/blob/1.12.x/src/main/java/nex/village/PigtificateVillage.java#L139
consider creating a single `MutableBlockPos` than calling `setPos()` on it, instead of creating `BlockPos` in every loop iteration.

**Comment by LogicTechCorp** [comment]
I implemented these changes in MineEx/NetherEx@b1ca5bf. The only thing I did not change was the world object in the PigtificateVillageData and PigtificateVillage classes as it is not too necessary. Do you have any other suggestions?

**Comment by LemADEC** [comment]
yes, using a weak reference to the WorldObj is necessary

**Comment by LogicTechCorp** [comment]
This has been resolved in MineEx/NetherEx@e487c4f. Any thing else you would like to add?

**Comment by LemADEC** [comment]
Looks good, let's see how it hold now on a live server :)

**Comment by LogicTechCorp** [comment]
Alright, the new build will be in a day or two.

**Comment by LogicTechCorp** [comment]
The new build is now out. Let me know if you have any other issues.
