### ISSUE TITLE
Server Crash on startup(NoSuchMethodError)  v2.0.7 (LibEx 1.0.7)

### ISSUE THREAD

**Issue by JoelZBub** [LogicTechCorp/NetherEx-Archive#116]
Forge Version : 1.12.2 forge-14.23.4.2757
NetherEx version : 1.12.2-2.0.7
LibEx version : 1.12.2-1.0.7

These were the only 2 mods I updated and server crashes on startup now. 
Rolling back to previously working versions NEx 2.0.6 and LibEx 1.0.6 until fixed. :)

Crash Report here: https://pastebin.com/yTCj1kVv

**Comment by LogicTechCorp** [comment]
This issue has been fixed in the latest version. Just waiting on Curse to approve it.

**Comment by JoelZBub** [comment]
Thank you
Next time I'll remember to check if there were any recent commits before reporting.....
