### ISSUE TITLE
[Suggestion] Allow TiCo Mattock for tilling soul sand

### ISSUE THREAD

**Issue by MasterEnderman** [LogicTechCorp/NetherEx-Archive#119]
Currently only the vanilla hoes are working. Would be nice to use the "hoes" of other mods aswell.

For exmaple the Flux infused Shovel from Redstone Arsenal works as Hoe while holding shift, but it doesn't work on Soulsand.

**Comment by Sewef** [comment]
I'm looking at the code (I'm bored).
- RS Arsenal's Shovel creates a UseHoeEvent
- TiCo simulates a Diamon_Hoe ItemUse

Currently in ClickHandler, the SouldSand tile action is in `onPlayerRightClick`. To solve the issue, I think the tile action needs to be in a separate `@SubscribeEvent public static void UseHoeEvent`.
Just saying, I like code analysing.
