### ISSUE TITLE
Ichor and lava for nether wart growing

### ISSUE THREAD

**Issue by FallenEagle1** [LogicTechCorp/NetherEx-Archive#120]
Just a suggestion while playing around with configs. Maybe the possibility to have a way that nether wart can be grown with both lava and ichor. I like having one or the other, but for some packs (thinking of a kitchen sink one right now) I could be good to allow both.

**Comment by LogicTechCorp** [comment]
Nether Wart growth will be changed back to the Vanilla system in the upcoming release.
