### ISSUE TITLE
Structures super rare/not spawning

### ISSUE THREAD

**Issue by jredfox** [LogicTechCorp/NetherEx-Archive#121]
All structures are very rare and or not spawning. The only structures I found after 3 hours of flying around was the pig village and it was small without the big guy and golden golem there. 

I was able to find one ghast queen structure and 5 pig villages but, again the villages were missing things. the rest of the 10 structures didn't spawn at all from what I could tell above and below y 60. There is no /locate addition to confirm this 100% but, they are alot more rare then it said on your forum here:
https://www.reddit.com/r/NetherEx/wiki/index

**Comment by LogicTechCorp** [comment]
Only one design of the Pigtificate Village and the Ghast Queen Shrine currently spawn. The others were removed for the time being as the system I use for generating the structures is not the best. I do plan on adding them back in eventually.

**Comment by drakray** [comment]
Can't wait, they seems awesome!
