### ISSUE TITLE
Biome selection at chunk generation is not dependent on seed

### ISSUE THREAD

**Issue by donqixot** [LogicTechCorp/NetherEx-Archive#122]
I am playing FS Lost Souls modpack and noticed very strange thing - if I generate certain new chunks, but then decide to go to backup from few days ago and if rebooted computer in between, then same chunks will have different biomes in them. It is always choices between BiomeOPlenty and NetherEx biomes which is different. I always assumed biome selection, just like terrain profile is dependent only on the seed of the world.

Here is another way to illustrate the problem. Say, some youtuber does series in a modpack which includes both BiomesOPlenty and NetherEx. He gives his viewers the seed of his world. Players who try to recreate his world will get different biomes at home, although terrain profile is the same. Even more bizare is the fact that if you reboot your computer and recreate the world again with the same seed, you will get different biomes again! If you do not reboot computer, then biomes are the same.

I looked through NEX issues and found some which refer to BOP biomes, but not to the biomes selection algorithm. If this is a known issue and there is a fix, I will update to latest version, but at the moment I am using latest version of the modpack, which includes version NetherEx-1.12-2.1.14.15 and BiomesOPlenty-1.12.2-7.0.1.2393-universal. If necessary I can create stand alone instance with only BOP and NetherEx latest versions and test, but first let me know if this is a known issue.

**Comment by donqixot** [comment]
I created standalone instance with only 2 mods - BOP and NEX, i cannot reproduce this issue there even with same version of forge and mods. So I will close this for now until I find exact mod which creates this issue.

**Comment by LogicTechCorp** [comment]
I was able to reproduce this too after some testing with only LEX and NEX installed. I'm going to reopen this so I can remember to look into this.

**Comment by donqixot** [comment]
Thanks! Really appreciate!

**Comment by LogicTechCorp** [comment]
I believe this issue has been fixed in newer versions.
