### ISSUE TITLE
Document New Biome Configuration Format

### ISSUE THREAD

**Issue by acook** [LogicTechCorp/NetherEx-Archive#123]
I have a set of fairly extensive biome modifications in NetherEx format that I am trying to convert to the new biome configuration format. 

For example, this is how I add an ore using the old Biome List format:
```json
                        {
                            "featureType": "ore",
                            "blockToSpawn": { "blockId": "tconstruct:ore", "meta": 1 },
                            "targetBlock": { "blockId": "nex:block_netherrack", "meta": 2 },
                            "size": 14,
                            "rarity": 16,
                            "minHeight": 10,
                            "maxHeight": 118
                        },
```
I'm able to specify `meta` for the block information here, but there doesn't seem to be such a feature in the new LibEx format.  This is just one example of undocumented features and things for which there appears to be no example to build off of. 

The [biome list documentation](https://www.reddit.com/r/NetherEx/wiki/configuration#wiki_biome_lists) is outdated but there is no other documentation that I can find for the new biome configuration format. I've been reading the source to LibEx to get a better handle on things, but some end-user documentation would really make my life easier.

**Comment by LogicTechCorp** [comment]
A lot has changed and I have been meaning to update the documentation, but I just don't have the time. You could try taking a look at the biome configs in the NetherEx config folder. Instead of using meta to get a block, you now have to use the block's properties. Here is an example of how the new format looks: 
```
{
	"feature": "lex:ore",
	"genStage": "ore",
	"blockToSpawn": {
		"block": "nex:quartz_ore",
		"properties": {
			"type": "lively"
		}
	},
	"blockToReplace": {
		"block": "nex:netherrack",
		"properties": {
			"type": "lively"
		}
	},
	"veinSize": 14,
	"minGenHeight": 10,
	"maxGenHeight": 108,
	"genProbability": 1.0,
	"genAttempts": 16,
	"randomizeGenAttempts": false,
	"generate": true
}
```

**Comment by acook** [comment]
Yeah, I have been looking at the existing biome configs. I guess what I'm not sure of is how to translate meta into properties/type for non-NetherEx blocks. How would I specify Cobalt Ore from Tinkers' Construct for example?

**Comment by LogicTechCorp** [comment]
It should be this:
```
"blockToSpawn": {
	"block": "tconstruct:ore",
	"properties": {
		"type": "cobalt"
	}
}
```
For ardite, you would replace "cobalt" with "ardite". The best way to get the block's properties is to look at it in-game, press F3 to open the debug menu, and look at the bottom right and it should tell you all of the block's properties. It shows as key=value. "key" would be in place of "type" and "value" would be in place of "cobalt".

**Comment by LogicTechCorp** [comment]
Closing this as the current versions of the biome configs should provide some more insight.

**Comment by acook** [comment]
Thanks!
