### ISSUE TITLE
Bedrock ceiling is broken, chunks pattern irregular

### ISSUE THREAD

**Issue by donqixot** [LogicTechCorp/NetherEx-Archive#124]
I am trying latest version NetherEx-1.12.2-2.0.8 along with BOP BiomesOPlenty-1.12.2-7.0.1.2399-universal and noticed that bedrock ceiling is broken in many places and also that chunk patterns is irregular. Here is picture of how map looks in editor "minutor", pink colors are non-vanilla blocks, you can see how chunks have irregular patterns. Is this a new feature since version NetherEx-1.12-2.1.14.15 or some side effect of changes being done?
![nex chunk patterns](https://user-images.githubusercontent.com/12219588/46312097-18fe0d80-c592-11e8-9ee1-d0bdf5dd3d20.png)

Here is picture of how bedrock ceiling is broken:
![nex bedrock ceiling](https://user-images.githubusercontent.com/12219588/46312204-637f8a00-c592-11e8-809a-c26b4e87809f.png)

Please note, broken patterns and bedrock ceiling are in BOP and Vanilla biome (Hell), but standalone BOP doesn't do that. Here is picture of the map with BOP only at level 126 - bedrock ceiling is not flat and there are no irregular patterns on chunk boundaries.
![nex - bop only](https://user-images.githubusercontent.com/12219588/46313063-e1449500-c594-11e8-9884-9ca51fdf78d0.png)

I am using latest forge 14.23.4.2765, it had some chunks changes done recently.

**Comment by donqixot** [comment]
It turns out, BoP also break bedrock ceiling, but not in the same pattern, see issue:
https://github.com/Glitchfiend/BiomesOPlenty/issues/1315

**Comment by LogicTechCorp** [comment]
This will be fixed in upcoming release.
