### ISSUE TITLE
Desync on attempt to plant netherwart on untilled soulsand

### ISSUE THREAD

**Issue by praecipitator** [LogicTechCorp/NetherEx-Archive#126]
Seems like when you attempt to plant netherwart on untilled soulsand while playing on a server, a desync happens. The netherwart disappears from your hand, but does not appear on the soul sand. It reappears in the inventory when reconnected, or somewhen later when the client is resynchronized.

Using NetherEx-1.12.2-2.0.8 on a forge-1.12.2-14.23.5.2768-universal server.

**Comment by LogicTechCorp** [comment]
Nether Wart growth will be changed back to the Vanilla system in the upcoming release.
