### ISSUE TITLE
Nether Wart Config Settings are not working

### ISSUE THREAD

**Issue by fandomaniac** [LogicTechCorp/NetherEx-Archive#127]
After one of the last update, the mod ignores these config settings:

soul_sand {
            B:allowAllHoesToTill=true
            B:doesNetherwartUseNewGrowthSystem=false

It only grows on tilled soul sand and you must use a Golden Wither Bone Hoe regardless of the config setting.

**Comment by Sewef** [comment]
According to
https://github.com/MineEx/NetherEx/blob/1.12.x/src/main/java/logictechcorp/netherex/handler/ConfigHandler.java#L79
the enable/disable config for soul_sand features has been removed :l

**Comment by atxmatt2510** [comment]
Does that mean we should remove those lines from the config?

**Comment by LogicTechCorp** [comment]
Nether Wart growth will be changed back to the Vanilla system in the upcoming release.
