### ISSUE TITLE
JourneyMap Mob Icon Integration

### ISSUE THREAD

**Issue by ghost** [LogicTechCorp/NetherEx-Archive#128]
Im working on a resource pack to add mob icons into JourneyMaps Minimap/Fullscreen Map
(https://minecraft.curseforge.com/projects/journeymap-mobs)

My icons for NetherEx are NOT showed on the maps and I believe its because the folder you keep your entity textures in is called "entities" and JourneyMap searches for "entity" foldername
(https://journeymap.info/Custom_Mob_Icon_Sets)

Would it be possible for you to make a test mod and rename the folder so I can try it, thank you

using NetherEx 1.12.2-2.0.8

**Comment by Sewef** [comment]
Entities → Entity
https://www.dropbox.com/s/6r6gt48i22wskon/NetherEx-1.12.2-2.0.9.jar?dl=0
Try this

**Comment by ghost** [comment]
Hi.  I need LibEx 1.0.9 to test it.  But opening the Jar and having a look everything seems ok

Thank you.  Its just one of those quality of life things like knowing which mobs are about to kill you, lol

**Comment by Sewef** [comment]
No problem, i'll PR this asap
