### ISSUE TITLE
Please Register Loot Tables to allow LootTweaker Integration (suggestion)

### ISSUE THREAD

**Issue by khift363** [LogicTechCorp/NetherEx-Archive#129]
In developing my modpack I discovered that NetherEX was not registering any loot tables for the mobs it adds. This is an issue because without appropriately registered loot tables the modpack development tool LootTweaker cannot edit the drops for a mob. I would love to use LootTweaker to add drops to the various NetherEX mobs as they make very frightening adversaries and they should have rewards that are appropriate for their difficulty, but unfortunately with unregistered loot tables I cannot do that.

To confirm that this wasn't a mod interaction with another mod in my pack, I made a new instance with the following details:

Minecraft v1.12.2
Forge v14.23.5.2795
CraftTweaker v4.1.13
LibEx v1.0.8
LootTweaker v0.0.8
NetherEX v2.0.8

In this instance, I created a new world and used the command "/ct loottables all" to dump all registered loot tables. I then checked in the "[Instance]\dumps\loot_tables" directory and confirmed that no loot tables were dumped that originated from NetherEX.

In the mean time, if you cannot push an update that registers this mod's loot tables for whatever reason, if you could post the locations of the loot tables within the mod I could potentially use that to hack together a way to edit the loot tables. Currently LootTweaker cannot do this, but in their upcoming 0.0.9 release they're adding a way to edit an unregistered loot table, but only if you already know its directory path. Without knowing where to write to that feature is insufficient - I need your help to find the directory path.

Thank you for your time and understanding.

**Comment by khift363** [comment]
I also understand that this would help enable integration with Just Enough Resources, a JEI addon that displays monster and chest loot. Like LootTweaker, JER finds the data it displays by using the list of registered loot tables, so if your loot tables are unregistered it cannot detect them. I'm not certain if it's automatic past that point or not, there may be another step, but I know getting the loot table registered is one of the steps.

**Comment by Sewef** [comment]
I'm working on, I hope the PR will be ready soon.

**Comment by Sewef** [comment]
It looks like JER can't read modded mobs' loottables properly, as a guy from ModdedMC Discord told me. And I can't get anything working using jei+jer api.
If you have an example of mod that made custom mob loottables, please tell me

**Comment by khift363** [comment]
My main desire isn't the JER compatibility, it's the ability to edit the loot tables via LootTweaker. JER compatibility becoming a possibility is just an extra bonus that comes alongside having registered loot tables.

Looking into it, it's definitely not automatic after registering the loot table. Plenty of mods in my modpack have registered loot tables, but I don't see any that have loot tables visible in JER. I know that JER claims that it's possible for mods to enable their loot tables to be read by it, but I don't really know how and I don't see any documentation on how to do it. You might be best served talking to the JER devs for that; looking at it now I probably shouldn'tve mentioned it as I don't see how I can help you with it sadly.

As for mods that have registered their loot tables, it's about a 50/50 split among the mods in my modpack. Various Oddities, Familiar Fauna, Botania, Immersive Engineering, Astral Sorcery, Twilight Forest, and Quark all have their mobs and dungeon chest loot tables registered and editable by LootTweaker. EnderIO, Thaumcraft, and Ice and Fire have some, but not all, of their loot tables registered. Other mods like DungeonMobsReborn have no registered loot tables.

**Comment by Sewef** [comment]
Okay. I'll take a new look on it asap!

**Comment by Sewef** [comment]
I got it!
![image](https://user-images.githubusercontent.com/27089398/50446181-d9865980-0913-11e9-9e97-b407351a43a9.png)

**Comment by Shadowless99** [comment]
I can't get the loottables. When I dump all tables with looktweaker, there is no folder for netherex. Am I doing something differently?

**Comment by LogicTechCorp** [comment]
This will be fixed in the upcoming release.
