### ISSUE TITLE
Mod Integration

### ISSUE THREAD

**Issue by Kyrinon** [LogicTechCorp/NetherEx-Archive#14]
While looking at the output from Biome Twaeker I noticed a few things that will make it difficult for your mod to integrate with other mods. All of your biomes have there temperature and humidity set to 0.5,  dictionary types set to "PLAINS", and rain enabled; all normal settings for plains but not the nether. humidity should probably be at 0.0 for all biomes. The nether temperature is normally 2.0 and has the dictionary types of "HOT", "DRY", "NETHER". Frozen biomes usually have a temperature of 0.0 and the dictionary type of "COLD". Some other dictionary types you may want to add are "MUSHROOM" and "WASTELAND"

**Comment by Kyrinon** [comment]
also as a side note do you need to modify the hell biome?

**Comment by LogicTechCorp** [comment]
What do you mean by "edit the hell biome"?

**Comment by Kyrinon** [comment]
I just noticed that your mod made the default "Hell" bime have the same parameters. With what little I know about how Forge handles biomes it seems that your biomes would be easily added to the nether without having to make any changes to the "Hell" biome.

**Comment by LogicTechCorp** [comment]
It is because I replaced the Hell biome with my own version and forgot to change it. I choose to replace it with a custom version that will allow the end user (you) to modify the biome via config. E.g. more Quartz ore, less Magma, or more Fire.

**Comment by Kyrinon** [comment]
Oh ya I saw those configs, very convenient by the way thanks
