### ISSUE TITLE
(1.12.2) Too many Zombies

### ISSUE THREAD

**Issue by Khanbit64** [LogicTechCorp/NetherEx-Archive#145]
I've went to the nether to find hundreds of zombies everywhere.
There are no spawn rate options for zombies in the config file. If anyone knows the problem or how to fix it please tell me.

Thanks.

![2019-03-09_23 01 22](https://user-images.githubusercontent.com/48395244/54078418-6f991180-42bf-11e9-88c1-73930cc2e051.png)

**Comment by CaptainSeven** [comment]
Do you have https://minecraft.curseforge.com/projects/multi-mob-core installed? I have the same issue and it seems that this might be related. Their most recent update indicates the possibility of excessive zombies...

**Comment by Khanbit64** [comment]
Yes I have MultiMobCore along with Primitive mobs and The summoner.
If MMC was the cause of this bug, then it would be a tough choice to remove
Nether Ex or MMC.

**Comment by LogicTechCorp** [comment]
I don't think this is a NetherEx issue.
