### ISSUE TITLE
[1.10.2-1.1.0] Glowstone doesn't seem to generate in the Nether

### ISSUE THREAD

**Issue by seanianjones** [LogicTechCorp/NetherEx-Archive#16]
Forge-12.18.2.2151

I haven't seen any Glowstone in the Nether with default config settings.

**Comment by LogicTechCorp** [comment]
@seanianjones This has been fixed and will be included in the next update.

**Comment by Saereth** [comment]
Any update on this for 1.10?

**Comment by LogicTechCorp** [comment]
NetherEx is under heavy development at the moment. The 1.10.x builds were for testing and feedback purposes. I plan on releasing NetherEx within the 1.11.x cycle. Sorry to disappoint but I really want the mod to feel polished and complete. @Saereth
