### ISSUE TITLE
Elder mushroom harvesting

### ISSUE THREAD

**Issue by LemADEC** [LogicTechCorp/NetherEx-Archive#167]
As of NetherEx-1.12.2-2.0.8, unlike vanilla, we can use the silk-touch enchantment to collect elder mushroom blocks.

**Comment by LemADEC** [comment]
On a related note, consider adding ore dictionary registration for mushroom items:
- plant
- mushroomAny  (see Quark)
- listAllmushroom  (see Pam's Harvestcraft)
and for the block themselves:
- blockMushroom

**Comment by LogicTechCorp** [comment]
This has been implemented in newer versions.
