### ISSUE TITLE
NetherEx not compatible with later Sponge versions?

### ISSUE THREAD

**Issue by NLBlacky** [LogicTechCorp/NetherEx-Archive#168]
NetherEx is causing a startup crash with Sponge (Version: spongeforge-1.12.2-2825-7.1.6-RC3764.jar). This is on version NetherEx-1.12.2-2.0.8.jar.

Crashlog: https://pastebin.com/5WZmNY93

In the past I was advised to disable Async lightning but this didn't fix it.

**Comment by LogicTechCorp** [comment]
I am not sure what the issue is. It says it can find things that should be there. Where did you download LEX and NEX?

**Comment by NLBlacky** [comment]
They were provided in the server pack for the modpack Stoneblock 2 version 1.14.0.
A more up to date Sponge fixed the issue so it must have been an error in Sponge.
