### ISSUE TITLE
Where are the loot tables?

### ISSUE THREAD

**Issue by katubug** [LogicTechCorp/NetherEx-Archive#169]
Hello! I am trying to disable the Wither Ash from dropping using LootTweaker. However, when I use the CraftTweaker command "/ct loottables all" - it doesn't dump a folder for NetherEx.

Thanks for your time!

**Comment by LogicTechCorp** [comment]
The way I added the drops does not allow for them to be removed. I already fixed this for the next update, but it won't be out for some time since I am heavily revamping the mod.

**Comment by katubug** [comment]
Ah, I understand. Thanks for your response! Good luck with the update,
looking forward to it! :)

**Comment by LogicTechCorp** [comment]
This will be fixed in the upcoming release.
