### ISSUE TITLE
Heated Quartz Ore dupe 

### ISSUE THREAD

**Issue by a-frenzy** [LogicTechCorp/NetherEx-Archive#17]
Place a heated quartz ore, mine with vanilla silk touch, press R or middle mouse for inventory sort, or don't do anything, you'll get 2 back

**Comment by LogicTechCorp** [comment]
Closing as the version used is heavily bugged and out of date.

**Comment by a-frenzy** [comment]
Using version 1.1.0b, the latest available on curseforge

**Comment by LogicTechCorp** [comment]
Yeah, that version is out of date and no longer supported. I am working on a new version for 1.11.2 that is a complete rewrite.
