### ISSUE TITLE
Ice has no temperature

### ISSUE THREAD

**Issue by lynaevm** [LogicTechCorp/NetherEx-Archive#173]
I would like to be able to use Frostburn Ice with a thermoelectric gen and, as far as I can tell, it has no temperature attached to it.  A cool temperature on frostburn and a colder temperature on a block of Rime would be great.

**Comment by LogicTechCorp** [comment]
There is no way to add a temperature to a block. This is done on whatever mod adds the thermoelectric gen.

**Comment by acook** [comment]
@lynaevm You can use CraftTweaker to specify the temperature of blocks.
