### ISSUE TITLE
[Issue/bug] Obsidian boat disappears when mined

### ISSUE THREAD

**Issue by Cryovolcano** [LogicTechCorp/NetherEx-Archive#174]
The obsidian boat is great to have in the nether, however, it is very hard to retrieve it since it just floats to the bottom of the lava/disappears when broken, this means you have to make a new boat every trip, or just leave it in the lava I guess.

I tried mining it with a magnetic enchantment, but it didn't go to inventory.

**Comment by LogicTechCorp** [comment]
This issue will be fixed in the next release.
