### ISSUE TITLE
Feature Request: Config Toggle To Disable Rewriting of Biome Jsons on World Load

### ISSUE THREAD

**Issue by TeetoKaziim** [LogicTechCorp/NetherEx-Archive#175]
I've edited the spawn rates of mobs in each of the biomes, and added custom spawns. But every time I restart my game and load a world, the mod automatically adds a large number of other-mod entity entries to the entities list.

Not only is this problematic when developing a modpack, but it is problematic for a player playing the pack long term: There doesn't seem to be any upper limit on how large these files will get, filling with duplicate after duplicate entry of mobs pulled from other mods entity spawning lists.

Further, while I'll admit I'm not sure how the spawning code works, it seems like having 50 entries for
```
    {
      "entity": "grimoireofgaia:baphomet",
      "creatureType": "monster",
      "weight": 10,
      "minGroupCount": 2,
      "maxGroupCount": 4,
      "spawn": true
    },
```
Might lead to a total weight of 500, crowding out other spawns you want to appear there?

**Comment by LogicTechCorp** [comment]
This should be fixed in the latest release.
