### ISSUE TITLE
Unexpected interaction with Charset based on ore dictionary entries

### ISSUE THREAD

**Issue by noobanidus** [LogicTechCorp/NetherEx-Archive#176]
The [Ore Dictionary entries for NetherEx](https://github.com/LogicTechCorp/NetherEx/blob/71c61ab0a4c543465490006cf7e097bd40a2a624/src/main/java/logictechcorp/netherex/init/NetherExOreDictionary.java) creates a key for "ore" which contains a number of items. 

Unfortunately, [this causes issues with Charset](https://github.com/CharsetMC/Charset/issues/414) which is expecting anything that has "ore" in it to be an actual ore dictionary entry. I'm not entirely sure whose side this is on -- it would certainly make sense for Charset to check the length of the string rather than relying on the assumption that the entry is more than just "ore".

On the other hand, "ore" is not a very descriptive and might cause confusion and conflict with other mods in the future.

**Comment by LogicTechCorp** [comment]
This issue has been fixed in the new version which is awaiting approval.

**Comment by noobanidus** [comment]
Awesome! Thanks so much for the response, I really appreciate it -- although I'm hopeful that charset will also fix it on their end as this surely won't be the last time someone has a weird interaction -- and nobody should be making that kind of expectation about the ore name that could cause an exception without testing it (in-code) first.
