### ISSUE TITLE
[Feature request] Make Nether wart growth configurable

### ISSUE THREAD

**Issue by ghost** [LogicTechCorp/NetherEx-Archive#177]
I noticed that nether wart growth has been changed back to the vanilla style, with Tilled Soul Sand being removed. Any chance that this could be re-added and maybe placed behind a config option? I'd like to update to the latest release of NetherEx, but I did rather like the nether wart growth mechanic and would love to see it return as an option.

Thanks for considering.

**Comment by LogicTechCorp** [comment]
There are no plans to re-add the old nether wart growth system.
