### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by WenXin20** [LogicTechCorp/NetherEx-Archive#178]
Minecraft 1.12.2
Forge v14.23.5.2838
NetherEx v2.0.10
LibraryEx v1.0.9

I get this crash after launching the game. It looks like it could be related to the Pigtificate Trade Config Manager.
[Crash Report](https://paste.dimdev.org/povijaqige.mccrash)

**Comment by LogicTechCorp** [comment]
Can you take a look through the Pigtificate trade configs and let me know what the values is for each profession?

**Comment by WenXin20** [comment]
Which values in the files are you looking for? I'm seeing multiple values for each profession. Or should I just send the files themselves?

**Comment by LogicTechCorp** [comment]
Are there multiple profession values in each file or just one? There should be a profession value, a career values, and a list of trades.

**Comment by WenXin20** [comment]
Ok, I see what you are looking for now. There's one profession in each file.
- netherex:smith for the amorsmith and toolsmith
- netherex:dimwit for the nincompoop
- netherex:forager for the scavenger, hunter, and gatherer
- netherex:sorcerer for the brewer and enchanter
- netherex:leader for the chief

**Comment by LogicTechCorp** [comment]
That all seems correct. Try deleting the trade configs and see if the the crash still happens.

**Comment by WenXin20** [comment]
Deleting the configs fixed the crash.
I'm not sure why it was causing t
It to crash before though.

**Comment by WenXin20** [comment]
Seems to be fixed now.
