### ISSUE TITLE
You can add this a zh_CN.lang 

### ISSUE THREAD

**Issue by Abo233** [LogicTechCorp/NetherEx-Archive#185]
99%汉化

**Comment by Abo233** [comment]
# Lang File Settings#波哥汉化
language.name=Chinese Simplified
language.region=China
language.code=zh_CN

# Config
config.netherex=下界拓展 - 配置

config.netherex:internal=内部设置
config.netherex:internal.tooltip=内部使用的设置
config.netherex:internal.doNotChange=不改变
config.netherex:internal.doNotChange.tooltip=不应被玩家改变的设定值
config.netherex:internal.doNotChange.warnBreakingChanges=警告中断更改
config.netherex:internal.doNotChange.warnBreakingChanges.tooltip=是否显示更改
config.netherex:internal.doNotChange.configVersion=设置文件版本
config.netherex:internal.doNotChange.configVersion.tooltip=设置置版本号

config.netherex:client=客户端设置
config.netherex:client.tooltip=只对客户端生效
config.netherex:client.visual=视觉设置
config.netherex:client.visual.tooltip=只影响客户端视觉效果的设置
config.netherex:client.visual.disableNetherFog=禁用下界雾
config.netherex:client.visual.disableNetherFog.tooltip=在下界是否渲染迷雾

config.netherex:compatibility=兼容性设置
config.netherex:compatibility.tooltip=针对模组兼容性的设置

config.netherex:compatibility.biomesOPlenty=超多生物群系兼容设置
config.netherex:compatibility.biomesOPlenty.tooltip=针对超多生物群系(BOP)的兼容性设置
config.netherex:compatibility.biomesOPlenty.enableCompatibility=启用超多生物群系兼容
config.netherex:compatibility.biomesOPlenty.enableCompatibility.tooltip=超多生物群系兼容是否启用

config.netherex:dimension=维度设置
config.netherex:dimension.tooltip=只针对维度的设置

config.netherex:dimension.nether=下界维度设置
config.netherex:dimension.nether.tooltip=针对下界维度的设置
config.netherex:dimension.nether.overrideNether=覆盖下界
config.netherex:dimension.nether.overrideNether.tooltip=是否使下界拓展覆盖下界
config.netherex:dimension.nether.generateSoulSand=生成灵魂沙
config.netherex:dimension.nether.generateSoulSand.tooltip=灵魂沙平台是否在下界生成
config.netherex:dimension.nether.generateGravel=生成砂砾
config.netherex:dimension.nether.generateGravel.tooltip=砂砾平台是否在下界生成
config.netherex:dimension.nether.isLavaInfinite=无限岩浆
config.netherex:dimension.nether.isLavaInfinite.tooltip=下界的岩浆是否无限

config.netherex:block=方块设置
config.netherex:block.tooltip=针对方块的设置

config.netherex:block.blueFire=蓝色火焰设置
config.netherex:block.blueFire.tooltip=仅针对蓝色火焰方块
config.netherex:block.blueFire.minEntityTicksAlight=最小实体燃烧时间
config.netherex:block.blueFire.minEntityTicksAlight.tooltip=能设定蓝色火焰的最小燃烧时间
config.netherex:block.blueFire.maxEntityTicksAlight=最大实体燃烧时间
config.netherex:block.blueFire.maxEntityTicksAlight.tooltip=能设定蓝色火焰的最大燃烧时间

config.netherex:block.netherPortal=下界传送门设置
config.netherex:block.netherPortal.tooltip=针对下界传送门方块的设置
config.netherex:block.netherPortal.pigmanSpawnRarity=猪人生成率
config.netherex:block.netherPortal.pigmanSpawnRarity.tooltip=下界传送门方块生成猪人的罕见程度

config.netherex:block.magma=岩浆块设置
config.netherex:block.magma.tooltip=针对岩浆块的设置
config.netherex:block.magma.turnIntoLavaWhenBroken=破坏时变成岩浆
config.netherex:block.magma.turnIntoLavaWhenBroken.tooltip=岩浆块是否在破坏时变成岩浆

config.netherex:block.rime=冰霜方块设置
config.netherex:block.rime.tooltip=针对冰霜方块的设置
config.netherex:block.rime.canFreezeWater=冻结水
config.netherex:block.rime.canFreezeWater.tooltip=冰霜方块是否能冻结水
config.netherex:block.rime.canFreezeLava=冻结岩浆
config.netherex:block.rime.canFreezeLava.tooltip=冰霜方块是否能冻结岩浆
config.netherex:block.rime.canFreezeMobs=冻结生物
config.netherex:block.rime.canFreezeMobs.tooltip=冰霜方块是否能冻结生物

config.netherex:block.thornstalk=荆棘设置
config.netherex:block.thornstalk.tooltip=针对荆棘的设置
config.netherex:block.thornstalk.canDestroyItems=破坏物品
config.netherex:block.thornstalk.canDestroyItems.tooltip=荆棘能否破坏物品
config.netherex:block.thornstalk.mobBlacklist=生物黑名单
config.netherex:block.thornstalk.mobBlacklist.tooltip=荆棘不会伤害的生物

config.netherex:block.hyphae=菌丝设置
config.netherex:block.hyphae.tooltip=针对菌丝的设置
config.netherex:block.hyphae.shouldSpread=菌丝是否蔓延
config.netherex:block.hyphae.shouldSpread.tooltip=菌丝是否蔓延到活地狱岩上

config.netherex:mobEffect=怪物药水效果设置
config.netherex:mobEffect.tooltip=针对怪物药水效果的设置
config.netherex:mobEffect.freeze=冻结效果设置
config.netherex:mobEffect.freeze.tooltip=针对冻结效果的设置
config.netherex:mobEffect.freeze.thawRarity=解冻罕见度
config.netherex:mobEffect.freeze.thawRarity.tooltip=一个生物从冻结状态解冻的罕见程度
config.netherex:mobEffect.freeze.mobBlacklist=怪物黑名单
config.netherex:mobEffect.freeze.mobBlacklist.tooltip=不会冻结的生物

config.netherex:mobEffect.spore=孢子效果设置
config.netherex:mobEffect.spore.tooltip=只影响孢子效果的设置
config.netherex:mobEffect.spore.sporeSpawnRarity=孢子生成罕见度
config.netherex:mobEffect.spore.sporeSpawnRarity.tooltip=带有孢子效果的实体召唤孢子的罕见度
config.netherex:mobEffect.spore.mobBlacklist=生物黑名单
config.netherex:mobEffect.spore.mobBlacklist.tooltip=不会召唤孢子的生物

config.netherex:mobEffect.lost=迷失效果设置
config.netherex:mobEffect.lost.tooltip=针对迷失效果的设置
config.netherex:mobEffect.lost.ghastlingSpawnRarity=小恶魂生成罕见度
config.netherex:mobEffect.lost.ghastlingSpawnRarity.tooltip=带有迷失效果的实体生成小恶魂的罕见度

config.netherex:entity=实体设置
config.netherex:entity.tooltip=针对实体的设置

config.netherex:entity.ember=余烬设置
config.netherex:entity.ember.tooltip=针对余烬的设置
config.netherex:entity.ember.setPlayerOnFireRarity=点燃玩家罕见度
config.netherex:entity.ember.setPlayerOnFireRarity.tooltip=余烬将玩家点燃的罕见度

config.netherex:entity.nethermite=地狱螨设置
config.netherex:entity.nethermite.tooltip=针对地狱螨的设置
config.netherex:entity.nethermite.spawnRarity=生成罕见度
config.netherex:entity.nethermite.spawnRarity.tooltip=地狱螨从地狱矿石中生成的罕见度
config.netherex:entity.nethermite.blockWhitelist=方块白名单
config.netherex:entity.nethermite.blockWhitelist.tooltip=地狱螨从这些方块中生成

config.netherex:entity.spinout=回旋石英刃设置
config.netherex:entity.spinout.tooltip=针对回旋石英刃的设置
config.netherex:entity.spinout.spinTime=旋转时间
config.netherex:entity.spinout.spinTime.tooltip=回旋石英刃的旋转时间
config.netherex:entity.spinout.spinCooldown=旋转冷却
config.netherex:entity.spinout.spinCooldown.tooltip=回旋石英刃两次旋转之间停止旋转的时长

config.netherex:entity.sporeCreeper=孢子爬行者设置
config.netherex:entity.sporeCreeper.tooltip=针对孢子爬行者的设置
config.netherex:entity.sporeCreeper.sporeSpawnRarity=生成孢子罕见度
config.netherex:entity.sporeCreeper.sporeSpawnRarity.tooltip=死亡时生成孢子的罕见度

config.netherex:entity.spore=孢子设置
config.netherex:entity.spore.tooltip=针对孢子的设置
config.netherex:entity.spore.growthTime=生长时间
config.netherex:entity.spore.growthTime.tooltip=孢子生长所需的时间
config.netherex:entity.spore.creeperSpawnAmount=爬行者召唤数量
config.netherex:entity.spore.creeperSpawnAmount.tooltip=每个孢子能生成的孢子苦力怕数量

config.netherex:entity.brute=蛮兽设置
config.netherex:entity.brute.tooltip=针对蛮兽的设置
config.netherex:entity.brute.chargeCooldown=冲刺冷却
config.netherex:entity.brute.chargeCooldown.tooltip=冲刺玩家之后的冷却时长

config.netherex:entity.ghastQueen=恶魂女王设置
config.netherex:entity.ghastQueen.tooltip=针对恶魂女王的设置
config.netherex:entity.ghastQueen.ghastlingSpawnCooldown=小恶魂生成冷却
config.netherex:entity.ghastQueen.ghastlingSpawnCooldown.tooltip=召唤小恶魂之后的冷却时长
config.netherex:entity.ghastQueen.ghastlingSpawnAmount=小恶魂召唤数量
config.netherex:entity.ghastQueen.ghastlingSpawnAmount.tooltip=当恶魂女王被攻击时召唤的小恶魂数量

config.netherex:biome=群系设置
config.netherex:biome.tooltip=针对群系的设置

config.netherex:biome.arcticAbyss=极地深渊群系设置
config.netherex:biome.arcticAbyss.tooltip=针对极地深渊群系的设置
config.netherex:biome.arcticAbyss.canPlayersFreeze=玩家是否冻结
config.netherex:biome.arcticAbyss.canPlayersFreeze.tooltip=玩家是否在极地深渊群系被冻结
config.netherex:biome.arcticAbyss.mobFreezeRarity=生物冻结罕见度
config.netherex:biome.arcticAbyss.mobFreezeRarity.tooltip=生物在极地深渊群系被冻结的罕见程度

# Messages
information.netherex:breaking_changes.1=NetherEx 已经将mod ID从 "nex" 改为 "netherex".
information.netherex:breaking_changes.2=下界拓展把它所有的物品和石块都夷为平地.
information.netherex:breaking_changes.3=因此，先前的生物群系/交易设置将被覆盖.
information.netherex:breaking_changes.4=如果对以前的配置进行了更改，则需要重新应用.
information.netherex:breaking_changes.5=如果您没有修改先前的生物群系/交易设置，则可以忽略此消息

# Creative Tabs
itemGroup.netherex=下界拓展

# Effects
mob_effect.netherex:frozen=冻结
mob_effect.netherex:frostbitten=冻伤
mob_effect.netherex:infested=感染
mob_effect.netherex:crying=哭泣
mob_effect.netherex:fire_buring=着火
mob_effect.netherex:soul_sucked=灵魂被吸走

# Potions
potion.effect.netherex:freezing=冻结药水
splash_potion.effect.netherex:freezing=喷溅型冻结药水
lingering_potion.effect.netherex:freezing=滞留型冻结药水
tipped_arrow.effect.netherex:freezing=冻结药水箭

potion.effect.netherex:frigid_health=冻伤药水
splash_potion.effect.netherex:frigid_health=喷溅型冻伤药水
lingering_potion.effect.netherex:frigid_health=滞留型冻伤药水
tipped_arrow.effect.netherex:frigid_health=冻伤药水箭

potion.effect.netherex:dispersal=感染药水
splash_potion.effect.netherex:dispersal=喷溅型冻伤药水
lingering_potion.effect.netherex:dispersal=滞留型感染药水
tipped_arrow.effect.netherex:dispersal=感染药水箭

potion.effect.netherex:sorrow=哭泣药水
splash_potion.effect.netherex:sorrow=喷溅型哭泣药水
lingering_potion.effect.netherex:sorrow=滞留型哭泣药水
tipped_arrow.effect.netherex:sorrow哭泣药水箭

# Entities (Mobs)
entity.netherex:ghast_queen_fireball.name=恶魂女王火球
entity.netherex:ghastling_fireball.name=小恶魂火球
entity.netherex:blue_fireball.name=蓝色火球
entity.netherex:obsidian_boat.name=黑曜石船
entity.netherex:pigtificate_leader.name=猪民领袖
entity.netherex:pigtificate_leader_chief.name=猪民长官
entity.netherex:pigtificate.name=猪民
entity.netherex:pigtificate_nincompoop.name=普通猪民
entity.netherex:pigtificate_hunter.name=猪民猎人
entity.netherex:pigtificate_gatherer.name=猪民采集者
entity.netherex:pigtificate_scavenger.name=猪民清道夫
entity.netherex:pigtificate_armorsmith.name=猪民铸甲师
entity.netherex:pigtificate_toolsmith.name=猪民工具匠
entity.netherex:pigtificate_enchanter.name=猪民附魔师
entity.netherex:pigtificate_brewer.name=猪民酿造师
entity.netherex:gold_golem.name=金傀儡
entity.netherex:mogus.name=魔菇
entity.netherex:brown_mogus.name=棕色魔菇
entity.netherex:red_mogus.name=红色魔菇
entity.netherex:white_mogus.name=白色魔菇
entity.netherex:salamander.name=火蜥蜴
entity.netherex:orange_salamander.name=橙色火蜥蜴
entity.netherex:black_salamander.name=黑色火蜥蜴
entity.netherex:wight.name=阴魂
entity.netherex:ember.name=余烬
entity.netherex:nethermite.name=地狱螨
entity.netherex:spinout.name=回旋石英刃
entity.netherex:lost_soul.name=迷失灵魂
entity.netherex:kind_lost_soul.name=善良的迷失灵魂
entity.netherex:timid_lost_soul.name=胆怯的迷失灵魂
entity.netherex:neutral_lost_soul.name=中立的迷失灵魂
entity.netherex:mean_lost_soul.name=意味着失去灵魂
entity.netherex:angry_lost_soul.name=愤怒的迷失灵魂
entity.netherex:ripper.name=Ripper
entity.netherex:spore_creeper.name=孢子苦力怕
entity.netherex:spore.name=孢子
entity.netherex:spore_one.name=一阶孢子
entity.netherex:spore_two.name=二阶孢子
entity.netherex:spore_three.name=三阶孢子
entity.netherex:spore_four.name=四阶孢子
entity.netherex:spore_five.name=五阶孢子
entity.netherex:ghastling.name=小恶魂
entity.netherex:coolmar_spider.name=骨蜘蛛
entity.netherex:brute.name=蛮兽
entity.netherex:frost.name=冻结
entity.netherex:ghast_queen.name=恶魂女王

# Fluids
fluid.netherex:blood.name=不朽之血

# Generators
generator.netherex:netherex=下界拓展

# Guis
gui.netherex:select_world.reset=重置
gui.netherex:select_world.reset_nether=刷新地狱
gui.netherex:select_world.reset_nether_question=你确定要重置地狱 %s?
gui.netherex:select_world.reset_nether_warning=% s的地狱将被重置回% s首次创建时!

# Items
item.netherex:fiery_netherbrick.name=火焰地狱砖
item.netherex:icy_netherbrick.name=冰冻地狱砖
item.netherex:lively_netherbrick.name=鲜活地狱砖
item.netherex:gloomy_netherbrick.name=灰暗地狱砖
item.netherex:wither_bone.name=凋灵骨
item.netherex:wither_dust.name=凋灵尘
item.netherex:frost_rod.name=冻结棒
item.netherex:frost_powder.name=冻结粉
item.netherex:blazed_wither_bone.name=黄金凋灵骨
item.netherex:frosted_wither_bone.name=霜冻之骨
item.netherex:orange_salamander_hide.name=橘色火蜥蜴皮
item.netherex:black_salamander_hide.name=黑色火蜥蜴皮
item.netherex:amethyst_crystal.name=下界紫晶
item.netherex:rime_crystal.name=下界霜晶
item.netherex:rime_and_steel.name=霜晶打火石
item.netherex:spore.name=孢子
item.netherex:coolmar_spider_fang.name=霜冻之牙
item.netherex:ripper_claw.name=Ripper Claw
item.netherex:ghast_queen_tear.name=恶魂女王之泪
item.netherex:obsidian_boat.name=黑曜石船
item.netherex:ghast_meat_raw.name=生恶魂肉
item.netherex:ghast_meat_cooked.name=熟恶魂肉
item.netherex:congealed_magma_cream.name=凝固岩浆膏
item.netherex:enoki_mushroom.name=金杵菇
item.netherex:dull_mirror.name=地狱定点魔镜
item.netherex:withered_amedian_sword.name=凋零骨剑
item.netherex:withered_amedian_pickaxe.name=凋零骨稿
item.netherex:withered_amedian_shovel.name=凋零骨铲
item.netherex:withered_amedian_axe.name=凋零骨斧
item.netherex:withered_amedian_hoe.name=凋零骨锄
item.netherex:withered_amedian_hammer.name=凋零骨锤
item.netherex:blazed_amedian_sword.name=黄金凋灵骨剑
item.netherex:blazed_amedian_pickaxe.name=黄金凋灵骨镐
item.netherex:blazed_amedian_shovel.name=黄金凋灵骨铲
item.netherex:blazed_amedian_axe.name=黄金凋灵骨斧
item.netherex:blazed_amedian_hoe.name=黄金凋灵骨锄
item.netherex:blazed_amedian_hammer.name=黄金凋灵骨锤
item.netherex:frosted_amedian_sword.name=冻结骨剑
item.netherex:frosted_amedian_pickaxe.name=冻结骨镐
item.netherex:frosted_amedian_shovel.name=冻结骨铲
item.netherex:frosted_amedian_axe.name=冻结骨斧
item.netherex:frosted_amedian_hoe.name=冻结骨锄
item.netherex:frosted_amedian_hammer.name=冻结骨锤
item.netherex:wither_bone_helmet.name=凋零骨头盔
item.netherex:wither_bone_chestplate.name=凋零骨胸甲
item.netherex:wither_bone_leggings.name=凋零骨护腿
item.netherex:wither_bone_boots.name=凋零骨靴子
item.netherex:orange_salamander_hide_helmet.name=橙色火蜥蜴头盔
item.netherex:orange_salamander_hide_chestplate.name=橙色火蜥蜴皮盔甲
item.netherex:orange_salamander_hide_leggings.name=橙色火蜥蜴皮护腿
item.netherex:orange_salamander_hide_boots.name=橙色火蜥蜴皮靴子
item.netherex:black_salamander_hide_helmet.name=黑色火蜥蜴头盔
item.netherex:black_salamander_hide_chestplate.name=黑色火蜥蜴胸甲
item.netherex:black_salamander_hide_leggings.name=黑色火蜥蜴护腿
item.netherex:black_salamander_hide_boots.name=黑色火蜥蜴皮靴子

# Subtitles
subtitle.netherex:sound.pigtificate_ambient=猪民:哼哼
subtitle.netherex:sound.pigtificate_hurt=猪民:受伤
subtitle.netherex:sound.pigtificate_death=猪民:死亡
subtitle.netherex:sound.mogus_ambient=魔菇:交谈
subtitle.netherex:sound.mogus_hurt=魔菇:畏缩
subtitle.netherex:sound.mogus_death=魔菇:死亡
subtitle.netherex:sound.salamander_ambient=火蜥蜴:咆哮
subtitle.netherex:sound.salamander_hurt=火蜥蜴:怒吼
subtitle.netherex:sound.salamander_death=火蜥蜴:死亡
subtitle.netherex:sound.wight_ambient=阴魂:低语
subtitle.netherex:sound.wight_hurt=阴魂:呻吟
subtitle.netherex:sound.wight_death=阴魂:死亡
subtitle.netherex:sound.ember_hurt=余烬:消逝
subtitle.netherex:sound.ember_death=余烬:熄灭
subtitle.netherex:sound.nethermite_ambient=地狱螨:吱吱
subtitle.netherex:sound.nethermite_hurt=地狱螨:尖叫
subtitle.netherex:sound.nethermite_death=地狱螨:死亡
subtitle.netherex:sound.spinout_ambient=回旋石英刃:旋转
subtitle.netherex:sound.spinout_hurt=回旋石英刃:受伤
subtitle.netherex:sound.spinout_death=回旋石英刃:死亡
subtitle.netherex:sound.ghastling_ambient=小恶魂:呻吟
subtitle.netherex:sound.ghastling_hurt=小恶魂:尖叫
subtitle.netherex:sound.ghastling_death=小恶魂:死亡
subtitle.netherex:sound.ghastling_warn=小恶魂:警报
subtitle.netherex:sound.ghastling_shoot=小恶魂:射击
subtitle.netherex:sound.spore_hurt=孢子:受伤
subtitle.netherex:sound.spore_death=孢子:死亡
subtitle.netherex:sound.spore_warn=孢子:咝咝
subtitle.netherex:sound.spore_explode=孢子:爆炸
subtitle.netherex:sound.ghast_queen_ambient=恶魂女王:呻吟
subtitle.netherex:sound.ghast_queen_hurt=恶魂女王:尖叫
subtitle.netherex:sound.ghast_queen_death=恶魂女王:死亡
subtitle.netherex:sound.ghast_queen_shoot=恶魂女王:火球
subtitle.netherex:sound.ghast_queen_summon=恶魂女王:召唤

# Tiles (Blocks)
tile.netherex:gloomy_netherrack.name=灰暗地狱岩
tile.netherex:lively_netherrack.name=鲜活地狱岩
tile.netherex:fiery_netherrack.name=火焰地狱岩
tile.netherex:icy_netherrack.name=霜冻地狱岩
tile.netherex:possessed_soul_sand.name=被附身的灵魂砂岩
tile.netherex:soul_sandstone.name=灵魂砂岩
tile.netherex:cut_soul_sandstone.name=切割灵魂砂岩
tile.netherex:chiseled_soul_sandstone.name=雕刻过的灵魂砂岩
tile.netherex:smooth_soul_sandstone.name=平滑灵魂砂岩
tile.netherex:basalt.name=玄武岩
tile.netherex:smooth_basalt.name=平滑玄武岩
tile.netherex:basalt_brick.name= 玄武岩砖
tile.netherex:basalt_pillar.name=玄武岩柱
tile.netherex:crying_obsidian.name=哭泣的黑曜石
tile.netherex:glowing_obsidian.name=发光的黑曜石
tile.netherex:gloomy_nether_brick.name=灰暗地狱砖
tile.netherex:lively_nether_brick.name=鲜活地狱砖
tile.netherex:fiery_nether_brick.name=火焰地狱砖
tile.netherex:icy_nether_brick.name=霜冻地狱砖
tile.netherex:netherrack_path.name=地狱岩石径
tile.netherex:gloomy_netherrack_path.name=灰暗地狱岩石径
tile.netherex:lively_netherrack_path.name=鲜活地狱岩石径
tile.netherex:fiery_netherrack_path.name=火焰地狱岩石径
tile.netherex:icy_netherrack_path.name=霜冻地狱岩石径
tile.netherex:hyphae.name=菌丝
tile.netherex:soul_glass.name=灵魂玻璃
tile.netherex:soul_glass_pane.name=灵魂玻璃板
tile.netherex:amethyst_block.name=下界紫晶块
tile.netherex:rime_block.name=下界冰霜块
tile.netherex:frostburn_ice.name=冻燃冰
tile.netherex:bone_sliver.name=骨板
tile.netherex:bone_chunk.name=骨块
tile.netherex:worn_iron.name=磨损铁块
tile.netherex:blue_fire.name=蓝火
tile.netherex:nether_portal.name=下界传送门
tile.netherex:urn_of_sorrow.name=悲伤的骨灰盒
tile.netherex:quartz_ore.name=下界石英矿石
tile.netherex:amethyst_ore.name=下界紫晶矿石
tile.netherex:rime_ore.name=下界冰霜矿石
tile.netherex:thornstalk.name=荆棘
tile.netherex:spoul_vines.name=Spoul Vines
tile.netherex:spoul_fruit.name=Spoul Fruit
tile.netherex:brown_elder_mushroom.name=棕色上古蘑菇
tile.netherex:red_elder_mushroom.name=红色上古蘑菇
tile.netherex:spoul_shroom.name=spoul
tile.netherex:brown_elder_mushroom_cap.name=棕色上古蘑菇帽
tile.netherex:red_elder_mushroom_cap.name=红色上古蘑菇帽
tile.netherex:enoki_mushroom_cap.name=金杵菇帽
tile.netherex:spoul_shroom_cap.name=spoul shroom cap
tile.netherex:elder_mushroom_stem.name=上古蘑菇茎秆
tile.netherex:enoki_mushroom_stem.name=金杵菇茎秆
tile.netherex:spoul_shroom_stem.name=spoul shroom stem
tile.netherex:ichor.name=不朽之血
tile.netherex:red_nether_brick_slab.name=红色地狱砖台阶
tile.netherex:fiery_nether_brick_slab.name=火焰地狱砖台阶
tile.netherex:icy_nether_brick_slab.name=霜冻地狱砖台阶
tile.netherex:lively_nether_brick_slab.name=鲜活地狱砖台阶
tile.netherex:gloomy_nether_brick_slab.name=灰暗地狱砖台阶
tile.netherex:soul_sandstone_slab.name=灵魂砂石台阶
tile.netherex:cut_soul_sandstone_slab.name=切割灵魂砂石台阶
tile.netherex:chiseled_soul_sandstone_slab.name=雕凿过的灵魂砂石台阶
tile.netherex:smooth_soul_sandstone_slab.name=平滑灵魂砂石台阶
tile.netherex:basalt_slab.name=玄武岩台阶
tile.netherex:smooth_basalt_slab.name=平滑玄武岩台阶
tile.netherex:basalt_brick_slab.name=玄武岩砖台阶
tile.netherex:basalt_pillar_slab.name=玄武岩柱板
tile.netherex:red_nether_brick_stairs.name=红色地狱砖楼梯
tile.netherex:fiery_nether_brick_stairs.name=火焰地狱砖楼梯 
tile.netherex:icy_nether_brick_stairs.name=霜冻地狱砖楼梯
tile.netherex:lively_nether_brick_stairs.name=鲜活地狱砖楼梯
tile.netherex:gloomy_nether_brick_stairs.name=灰暗地狱砖楼梯
tile.netherex:soul_sandstone_stairs.name=灵魂砂石楼梯
tile.netherex:cut_soul_sandstone_stairs.name=切割灵魂砂石楼梯
tile.netherex:chiseled_soul_sandstone_stairs.name=雕凿过的灵魂砂石楼梯
tile.netherex:smooth_soul_sandstone_stairs.name=平滑灵魂砂石楼梯
tile.netherex:basalt_stairs.name=玄武岩楼梯
tile.netherex:smooth_basalt_stairs.name=平滑玄武岩楼梯
tile.netherex:basalt_brick_stairs.name=玄武岩楼梯
tile.netherex:basalt_pillar_stairs.name=玄武岩柱楼梯
tile.netherex:quartz_wall.name=石英墙
tile.netherex:nether_brick_wall.name=地狱砖墙
tile.netherex:red_nether_brick_wall.name=红色地狱砖墙
tile.netherex:gloomy_nether_brick_wall.name=灰暗地狱砖墙
tile.netherex:lively_nether_brick_wall.name=鲜活地狱砖墙
tile.netherex:fiery_nether_brick_wall.name=火焰地狱砖墙
tile.netherex:icy_nether_brick_wall.name=霜冻地狱砖墙
tile.netherex:soul_sandstone_wall.name=灵魂砂石墙
tile.netherex:cut_soul_sandstone_wall.name=切割灵魂砂石墙
tile.netherex:chiseled_soul_sandstone_wall.name=雕凿过的灵魂砂石墙
tile.netherex:smooth_soul_sandstone_wall.name=平滑灵魂砂石墙
tile.netherex:basalt_wall.name=玄武岩墙
tile.netherex:smooth_basalt_wall.name=平滑玄武岩墙
tile.netherex:basalt_brick_wall.name=玄武岩砖墙
tile.netherex:basalt_pillar_wall.name=玄武岩柱墙
tile.netherex:quartz_fence.name=石英栅栏
tile.netherex:red_nether_brick_fence.name=红色地狱砖栅栏
tile.netherex:gloomy_nether_brick_fence.name=灰暗地狱砖栅栏
tile.netherex:lively_nether_brick_fence.name=鲜活地狱砖栅栏
tile.netherex:fiery_nether_brick_fence.name=火焰地狱砖栅栏
tile.netherex:icy_nether_brick_fence.name=霜冻地狱砖栅栏
tile.netherex:basalt_fence.name=玄武岩砖
tile.netherex:smooth_basalt_fence.name=平滑玄武岩栅栏
tile.netherex:basalt_brick_fence.name=玄武岩栅栏
tile.netherex:basalt_pillar_fence.name=玄武岩柱栅栏
tile.netherex:quartz_fence_gate.name=石英楼梯
tile.netherex:nether_brick_fence_gate.name=地狱砖栅栏门
tile.netherex:red_nether_brick_fence_gate.name=红色地狱砖栅栏门
tile.netherex:gloomy_nether_brick_fence_gate.name=灰暗地狱砖栅栏门
tile.netherex:lively_nether_brick_fence_gate.name=鲜活地狱砖栅栏门
tile.netherex:fiery_nether_brick_fence_gate.name=火焰地狱砖栅栏门
tile.netherex:icy_nether_brick_fence_gate.name=霜冻地狱砖栅栏门
tile.netherex:basalt_fence_gate.name=玄武岩栅栏门
tile.netherex:smooth_basalt_fence_gate.name=平滑玄武岩栅栏门
tile.netherex:basalt_brick_fence_gate.name=玄武岩砖栅栏门
tile.netherex:basalt_pillar_fence_gate.name=玄武岩柱栅栏门

# Tooltips
tooltip.netherex:dull_mirror.spawn_dimension=§a出生维度: %s
tooltip.netherex:dull_mirror.spawn_point=§9出生点: %s
tooltip.netherex:dull_mirror.spawn_point_set=§9生成点设定: %s
tooltip.netherex:dull_mirror.spawn_point_removed=§c出生点已删除
tooltip.netherex:dull_mirror.death_point=§c死亡点: %s

**Comment by Abo233** [comment]
望采纳哦！

**Comment by ChirenCQR** [comment]
你这明显有些翻译是错误的

**Comment by LogicTechCorp** [comment]
This will be added in the next release.
