### ISSUE TITLE
Bonemealing a sapling crashes client playing on a server

### ISSUE THREAD

**Issue by nathandstory** [LogicTechCorp/NetherEx-Archive#187]
Link to recent conversation that lead to NetherEx as being the cause:
https://github.com/Cryptic-Mushroom/The-Midnight/issues/290

When I bone meal a sapling (have tried both Pam's Harvestcraft and Silverwood sapling from thaumcraft) my client crashes. Another user (without Open Terrain Gen) seems to be experiencing a similar error.  I am using NetherEx version 1.12.2-2.0.12, any help would be much appreciated:

java.lang.NullPointerException: Unexpected error at com.pg85.otg.forge.ForgeWorld.getObjectSpawner(ForgeWorld.java:1349) at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:586) at com.pg85.otg.forge.ForgeWorld.getMaterial(ForgeWorld.java:782) at com.pg85.otg.forge.events.SaplingListener$SaplingGrower.<init>(SaplingListener.java:38) at com.pg85.otg.forge.events.SaplingListener$SaplingGrower.<init>(SaplingListener.java:27) at com.pg85.otg.forge.events.SaplingListener.onSaplingGrow(SaplingListener.java:169) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2242_SaplingListener_onSaplingGrow_SaplingGrowTreeEvent.invoke(.dynamic) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) at net.minecraftforge.event.terraingen.TerrainGen.saplingGrowTree(TerrainGen.java:108) at thaumcraft.common.blocks.world.plants.BlockSaplingTC.generateTree(BlockSaplingTC.java:87) at thaumcraft.common.blocks.world.plants.BlockSaplingTC.grow(BlockSaplingTC.java:81) at thaumcraft.common.blocks.world.plants.BlockSaplingTC.func_176474_b(BlockSaplingTC.java:172) at logictechcorp.netherex.handler.InputHandler.onBoneMealUse(InputHandler.java:177) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_722_InputHandler_onBoneMealUse_BonemealEvent.invoke(.dynamic) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) at net.minecraftforge.event.ForgeEventFactory.onApplyBonemeal(ForgeEventFactory.java:455) at net.minecraft.item.ItemDye.applyBonemeal(ItemDye.java:111) at net.minecraft.item.ItemDye.func_180614_a(ItemDye.java:55) at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:187) at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:477) at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96) at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579) at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254) at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020) at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808) at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) at net.minecraft.client.main.Main.main(SourceFile:123) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) at net.minecraft.launchwrapper.Launch.main(Launch.java:28)``

**Comment by LogicTechCorp** [comment]
This has been fixed in the latest version.
