### ISSUE TITLE
Nether ores fortune into themselves causing item duplication

### ISSUE THREAD

**Issue by Seraphaestus** [LogicTechCorp/NetherEx-Archive#188]
When you mine a Rime or Amethyst ore with a Fortune pickaxe, the block drops multiple items of itself, where instead it should drop multiple items of its corresponding gem.

This results in item duplication, e.g. Mine 1 amethyst ore with fortune 3, I end up with 5 amethyst ores.

**Comment by LogicTechCorp** [comment]
This has been fixed in the latest version.
