### ISSUE TITLE
Question: Taming Mobs.

### ISSUE THREAD

**Issue by 63502** [LogicTechCorp/NetherEx-Archive#19]
Will there ever be mobs that can be tamed? I am not just talking about like with wolves with the whole feed-bone-get-dog deal. Would it be possible to make special mobs that can be tamed through more complex means? 

This mod has taken very cool approach to augmenting the nether, and I am very impressed by it so far. If you want any of my ideas on different kinds of tamable mobs that could fit within the theme of the mod, I would be more than happy to share them.

Regardless of your answer, I look forward to what this mod can do in the future. 
Keep up the great work. :)

**Comment by LogicTechCorp** [comment]
I am not sure about tamable mobs at this point in time, but I would like to hear your ideas on them.

**Comment by 63502** [comment]
Alright, I will flesh out a few of my best ideas and post them here in a few days. :)

**Comment by 63502** [comment]
This is my current best idea. If you need clarification on anything, please tell me. :)

Hell Bats: 
_“Totally not inspired by Thaumcraft……… no, really.”_

- **Lore Text(rough draft):**
Hell bats are big reddish brown creatures with thick manes, oddly wolf-like heads, enormous leathery wings, and glowing red eyes. Their vicious appearance is actually quite deceiving however, as it hides a much less aggressive nature than most other denizens of the Nether. Hell bats roost in the high reaches of the most open parts of the sprawling hellscape, and if curious adventurers get close enough, they will turn to stare as they pass. 
While not innately aggressive, Hell Bats are very protective of their colony. They will encircle any who approach too fast and screech at them until they leave. Any who attack them directly rarely survive. 
Taming hell bats is possible, since they are quite smart creatures. When tamed, they attack any monsters within 5 blocks of their owner, as well as warning off other unsavory creatures and players.

- **General Information:**
**Stats(subject to change as necessary for balance):**
15 (7.5 hearts) untamed
30 (15 hearts) tamed
**Damage:**
6 (3 hearts) main attack + 1 per difficulty level (including tamed)
**Secondary effect**
Leeches health equal to 50% of damage dealt
**Attack speed:**
Slow

- **Size:**
Same as a wolf.
Wingspan is larger in proportion to its body than a normal bat.

- **Specific Features:**
Head is wolflike, but with much larger ears.
Has Hind legs with claws that are used to cling to ceilings as well as crawl along the ground.
Wings have four states unlike vanilla counterparts.
Unfurled for flying.
Folded for roosting upside down.
Partially folded for crawling on the ground.
![vampire_bat_crawl](https://user-images.githubusercontent.com/15267053/28198911-83ba0e10-682f-11e7-9eee-0c2b487c5c82.jpg)
Partial unfolded threat display for when players approach roost while sprinting.
![bat](https://user-images.githubusercontent.com/15267053/28198916-8c92e6ba-682f-11e7-9b07-269bebdfa68d.jpg)

- **Coloration**
Fur is a dark reddish color, not unlike that of gloomy nether brick.
Eyes glow in the dark and at distance.

- **Behavior**
**When passive:**
Hangs on the nether ceiling in colonies of 5-9, gazing directly and intently at any players that sneak or walk within 16 blocks.
Occasionally drops into flight for a short while.
Actively hunts and kills any nearby ghasts.
**When approached non-aggressively:**
Turns to face the player directly, watching as long as the player is within 16 blocks.
**When approached aggressively:**
Unfurls its wings in a menacing manner if the player gets within 10 blocks of the colony while sprinting. Slowly folds wings if the player stops running.
Drops into flight and engages in a vex-like flight pattern around the player. Makes screeching noises and breathes harmless sparks of flame and smoke while doing so.
**When attacked:**
All colony members attack the player in a vex-like manner(without noclip, as they aren’t ghosts), flying away when at low health.

- **Taming**
**Materials:**
6-8 Raw Ghast Meat
Any possible materials for making a reasonable (5x5-9x9) platform to stand on, blast proof if possible because Ghast Spleefing.
**Steps to tame:**
Approach while walking or sneaking until you see many red eyes.
Hold Ghast Meat in your main hand(nothing in offhand) and wait for a bat to approach you.
If it flies away, wait until it comes back.
If it lands on the ground and crawls closer, sneak closer and feed it the Ghast Meat.
The bat will then show tame hearts, its eyes will turn purple, and it will get 15 extra health.
Shift right click to pick up you new friend.
**Behavior when tame:**
Follows the player while flying.
_Possible cool feature(may not be practical or possible to implement):
It can follow its owner’s exact path at the same speed within 5 blocks if its owner is flying with elytra.
Will toggle between finding a roost on nearby 2+ block high ceilings to its owner and constantly flying/ guarding its owner when right clicked._
Will drop to the ground if shift right clicked while flying. If shift right clicked while crawling, it will climb onto the player’s back.
When on its owner’s back, it will make hissing noises if hostile mobs are nearby. It will also grasp its owner with its hind claws and attempt to slow his/her fall for up to 10 seconds before tiring out for 20 seconds
Breeding involves feeding two tame bats 3 Raw Ghast Meat each while they are crawling on the ground.

**Comment by 63502** [comment]
So, what do you think?

(I have another idea that involves a cross between hellhounds and demons, but it's taking a while to hammer out the details.)

**Comment by LogicTechCorp** [comment]
It is a really nice idea, but it seems too complicated for me to implement as I am not the best at making complex mobs.
