### ISSUE TITLE
Soul sand spreading on overworld beaches after update

### ISSUE THREAD

**Issue by capt-slowpoke** [LogicTechCorp/NetherEx-Archive#191]
I just recently updated to 1.12.2-2.0.13 from the previous version and I've got patches of soul sand that are quickly spreading on a beach in the overworld. What might be causing this? Everything else is working fine and I've gotten a significant performance improvement over the last version. 
All my other mods have stayed the same.

**Comment by LogicTechCorp** [comment]
I don't think that issue is related to NEX as I don't modify anything related to sand or soul sand.

**Comment by 12foo** [comment]
Do you have Charm installed by any chance? Charm's Spectres are invisible and turn sand into soul sand when they touch it. They like to spawn around stronghold entrances or other spooky/very dark areas, and one may be under your beach. Dunno if nether portals count as well.

**Comment by LogicTechCorp** [comment]
This issue is not caused by NetherEx.
