### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by inkdear** [LogicTechCorp/NetherEx-Archive#194]
"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from NetherEx (netherex)"

Crash report:
[crash-2019-09-12_19.43.36-client.txt](https://github.com/LogicTechCorp/NetherEx/files/3604298/crash-2019-09-12_19.43.36-client.txt)

Modlist:
![moslist](https://user-images.githubusercontent.com/41709276/64764490-47ec7400-d596-11e9-81ed-b8b3b2496bd4.png)

**Comment by Compegen** [comment]
Try deleting your netherex configs & restarting the game

**Comment by inkdear** [comment]
That was it, thank you. The weird thing is it worked with the old configs for one launch and then didn't work the second time.

**Comment by Gunner76th** [comment]
This issue has already been resolved. You need to use the most recent release of NetherEx. https://github.com/LogicTechCorp/NetherEx/issues/192
