### ISSUE TITLE
Nether quartz ores no longer respect silk touch

### ISSUE THREAD

**Issue by MrPipperz** [LogicTechCorp/NetherEx-Archive#195]
As the title says. Vanilla and modded silk touch tested. Have tested in latest (.15)

Mod environment was ATM3:Remix pack.

Edit: Have tested in standalone environment, same behavior. Vanilla quartz ore behaves correctly, it appears only to affect the biome-specific quartz ores added.

**Comment by LogicTechCorp** [comment]
This issue will be fixed in the next release.
