### ISSUE TITLE
Still getting the start up crash on newest version

### ISSUE THREAD

**Issue by breadguyyy** [LogicTechCorp/NetherEx-Archive#196]
https://paste.dimdev.org/ucezabitex.mccrash

ive re-genned the config like 3 times and it crashes on start up on my 3rd load up every time

**Comment by LogicTechCorp** [comment]
What config did you delete? Did you try to modify any configs?

**Comment by breadguyyy** [comment]
i deleted the netherex folder in configs and no i just let it generate the default and didnt touch it. it was weird though, it didnt crash the first or second time it crashed on the third load up

**Comment by pabthelamb** [comment]
I am experiencing this issue as well.

**Comment by LogicTechCorp** [comment]
This issue has been fixed in newer versions.
