### ISSUE TITLE
Minecraft failed to start

### ISSUE THREAD

**Issue by SxyDragon** [LogicTechCorp/NetherEx-Archive#197]
Midway through loading up a modpack minecraft failed and said it couldnt load because of NetherEx.
Heres the crash report link https://paste.dimdev.org/mucacupuki.mccrash

**Comment by Gunner76th** [comment]
This issue has already been resolved. You need to use the most recent release of NetherEx. https://github.com/LogicTechCorp/NetherEx/issues/192
