### ISSUE TITLE
Plains biome spawns in Nether, creating MASSIVE gaping holes everywhere

### ISSUE THREAD

**Issue by TheVisionaryOne** [LogicTechCorp/NetherEx-Archive#199]
For some reason, NetherEx is generating a "plains.json" file in its minecraft biomes folder (config>netherex>biomes>minecraft). This causes actual overworld plains biomes to spawn in the nether, which produces HUGE gaping holes in the world.

Screenshot: (https://cdn.discordapp.com/attachments/362322551684464643/630564828565471242/2019-10-06_16.59.13.png)

It looks really ugly, and I haven't found a fix for it. Deleting the json file doesn't work, because a new one will generate in its place. Replacing the text of the json file with a different biome doesn't work either.

(For reference, I'm using version 1.12.2)

**Comment by LogicTechCorp** [comment]
If the plains biome is being generated that means that there is an issue with another biome. Did it suddenly occur? Is this in a new world or an old world? Did you update any mods recently? Can you also send me the plains.json?

**Comment by TheVisionaryOne** [comment]
The problem occurred only on the second world I created with NetherEx. I was testing a modpack, and installed NetherEx to see if it was compatible with my pack. Everything generated perfectly fine for the first world, and then I generated another one (same session, no new mods or anything), and I started seeing plains biomes everywhere. That should hopefully answer most of your questions.

[Here's](https://github.com/LogicTechCorp/NetherEx/files/3695655/plains.txt) the plains.json (I converted it to .txt so I could upload it to GitHub).

Also, [here's](https://github.com/LogicTechCorp/NetherEx/files/3695662/mod-list_2019-10-06_17.11.26.txt) my modlist, in case it might be helpful.

**Comment by LogicTechCorp** [comment]
If you remove Biome O' Plenty, does the issue still occur?

**Comment by katubug** [comment]
@TheVisionaryOne Could you also include your Forge version? I just tossed NetherEx/LibEx into a testing instance with forge 2838 and I don't have a plains.json anywhere in the NetherEx config folder. I also threw BoP in there and ran it again - still no plains.json.

* **Minecraft version:** 1.12.2
* **Forge version:** forge-1.12.2-14.23.5.2838-universal
* **Mod versions:** NetherEx-1.12.2-2.0.15, LibraryEx-1.12.2-1.0.12, BiomesOPlenty-1.12.2-7.0.1.2441-universal

Edit: I did just compare your plains.json to the `/minecraft/hell.json` and they do match in terms of syntax and setup. So I'm not sure what's going on.

Edit 2: I also have a workaround for you:

A) Go into the plains.json and change "isEnabled" to `false`. This should at least stop holes from generating.

or

B) Copy over the contents of the hell.json and overwrite what's in the plains.json. This should cause the "plains" biome to spawn as a hell biome instead.

The reason it's generating as gaping holes is because in the plains.json there are no blocks defined for the biome to be made out of. As to why the plains.json is generating at all, that's beyond me. It'll be on you and the devs to work out, but I'll help if I can.

**Comment by TheVisionaryOne** [comment]
@LogicTechCorp I thought I had already tested Biomes O' Plenty, but I guess not! I removed it from my modpack, and the Nether looks fine now. It's interesting that katubug was able to run both Biomes O' Plenty and NetherEx together without any problems.

@katubug I tried both changing "isEnabled" to false in the plains.json, and copy-pasting the contents of hell.json into plains.json. Neither worked, and the plains.json file was reset to its default contents once I created the second world since updating the file. I am using a newer Forge version, but that shouldn't matter much, right?

I tested worldtypes (and disabled Climatic Biomes 2, which provided the main worldtype I was using for testing), but all of them had these broken plains biomes in the nether. Even the default worldtype had them, which doesn't spawn Biomes O' Plenty blocks/biomes. I think I'm even more confused than before.

**Comment by katubug** [comment]
If you create a new instance with just NetherEx/LibEx, does the plains.json still generate? That's such a bizarre error, I can't imagine what else could be interfering with it. I would *assume* that Forge hasn't changed enough from 2838 to 2847 to cause a bug on that scale, but if I know anything about technology, I wouldn't rule it out.

**Comment by LogicTechCorp** [comment]
@TheVisionaryOne Which versions of LibraryEx, NetherEx, and BOP are you using?

**Comment by TheVisionaryOne** [comment]
@katubug I tried creating a test environment in Forge 2847, and no plains.json file generated. Some other mod must be causing the problem...but it's absolutely bizarre that another mod is generating files in NetherEx's folders. Unless NetherEx has some sort of broken compatibility integration with another mod, it seems like NetherEx is completely unrelated?

@LogicTechCorp I'm using the most recent versions of all mods in question for 1.12.2. Biomes O' Plenty 7.0.1.2441, LibraryEx 1.0.12, and NetherEx 2.0.15.

I'm really not sure where to go from here. Like I said, I already tried disabling Climatic Biomes 2 (which is the only other biome-generating mod in my pack that I can think of), and nothing changed.

**Comment by LogicTechCorp** [comment]
I am not sure where the issue lies. The plains biome generating is purposeful on my end, but it is to signify that there is an issue.

**Comment by katubug** [comment]
@TheVisionaryOne You mentioned you had one of the BoP nether biomes disabled, right? Does the issue still occur if you re-enable it?

I guess at this point, troubleshooting wise, the best option is to do the half-and-half method until you find the mod that's causing it.

If you can get me a modlist with version numbers (via screenshot, maybe) I can help you nail it down.

**Comment by TheVisionaryOne** [comment]
So it _is_ an intended part of the program. That makes a little more sense than it just randomly showing up. Still weird that there's an...issue? The biggest issue is the plains biome itself. xD

@katubug I did disable a BoP biome, and at first, I thought that was the cause. I tested re-enabling the biome, but it didn't fix anything. I'm really confused about what's causing this, and I would like to get to the bottom of it, but I just don't have the time to go mod-by-mod.

@LogicTechCorp If the plains biome json is programmed to mark an issue, is there any sort of log or copy/paste text I could send you that would help you nail down what the issue might be?

**Comment by LogicTechCorp** [comment]
@TheVisionaryOne Try re-enabling the BOP biome, delete the NEX biome config folder, start the game to regenerate the configs, and then disable the BOP biome via the NEX biome config for the biome.

**Comment by katubug** [comment]
I know you said you disabled climatic biomes - what about Geographicraft? Could that be affecting it?

**Comment by TheVisionaryOne** [comment]
@LogicTechCorp You're a genius! Originally, I didn't realize that biomes could be disabled through NetherEx, so I went straight to BoP instead. Re-enabling the biome through BoP and then disabling the biome through NetherEx fixed the problem completely.

**Comment by TheVisionaryOne** [comment]
@katubug Thanks for your help troubleshooting the problem as well!
