### ISSUE TITLE
Coolmar Spider Legs interact weirdly with Frostburn Ice

### ISSUE THREAD

**Issue by katubug** [LogicTechCorp/NetherEx-Archive#200]
Hello! I have a small one for you today. It was mentioned by someone in one of my discords, and since I could replicate the issue in their screenshots, I offered to report it.

When Coolmar Spiders walk on Frostburn Ice, their legs do an ex-ray effect through the ice. Here's an imgur album (top 3 screens are theirs, bottom is mine):

https://imgur.com/a/t68Vrar

I tested in a limited modlist while I was working on that issue with Visionary. Here it is: https://puu.sh/Eq3ld/45574e31ed.png

Forge is 2838. NetherEx is 2.0.15 and LibEx is 1.0.12.

Let me know if you need any other information, thank you! :)

**Comment by Sunconure11** [comment]
Someone I know also encountered this. @LogicTechCorp

**Comment by LogicTechCorp** [comment]
This issue has been fixed in newer versions.
