### ISSUE TITLE
NetherEx Quartz ore blocks are transparent/xray while in Biomes O Plenty biomes

### ISSUE THREAD

**Issue by katubug** [LogicTechCorp/NetherEx-Archive#201]
* **Minecraft version:** 1.12.2
* **Forge version:** forge-1.12.2-14.23.5.2838-universal
* **Modpack version** (links to current modlist): [1.7.3](http://enthusiasticraft.cf/modpack-update-1-7-3/#modlist)
* **Mod versions:** NetherEx-1.12.2-2.0.15, LibraryEx-1.12.2-1.0.12, BiomesOPlenty-1.12.2-7.0.1.2441-universal

One of my players sent me the following screenshot: 
![unknown](https://user-images.githubusercontent.com/20935286/66709722-ad678800-ed2f-11e9-86e3-b342afef83f3.png)

I logged into the server to check it out, and sure enough, the block seemed to have no texture, allowing people to see through the world. It's difficult to see in just a screenshot, so here's a video to show what I mean: https://gfycat.com/temptingchillyeel

In the creative menu, one's inventory, and JEI, it appears transparent (although I think this might be intended, because when placed it adopts textures based on biome, right?):
![2019-10-12_20 09 15](https://user-images.githubusercontent.com/20935286/66709584-f4a04980-ed2c-11e9-8937-a2b9fbcceeaf.png)

It seems to place correctly in the overworld and Twilight Forest. The biome in the screenshot is from Project: Vibrant Journeys.
![2019-10-12_20 08 54](https://user-images.githubusercontent.com/20935286/66709585-f66a0d00-ed2c-11e9-8012-8936a4aa6be9.png)

And I discovered this while doing some testing - it works fine in NetherEx biomes and in vanilla Hell biomes. But in ones added by Biomes O Plenty, it fails to pick up a texture. These screenshots were taken in a limited modlist with just NetherEx, BoP, and some assorted QoL mods to make testing easier.
![2019-10-12_20 28 39](https://user-images.githubusercontent.com/20935286/66709716-7db88000-ed2f-11e9-9c64-4e2c5451985c.png)
![2019-10-12_20 28 42](https://user-images.githubusercontent.com/20935286/66709717-7db88000-ed2f-11e9-97c4-11d10b664815.png)

After doing some slightly more rigorous testing, I feel confident that this is only an issue with BoP biomes, although I have not been entirely comprehensive in checking biomes from all the mods that I have.

Hopefully this is enough to go on, but if you need more information, please let me know! Thank you! :)

**Comment by ghost** [comment]
I too have encountered this issue in my modpack as well. I can confirm that it only appears to happen in BoP Biomes.

Minecraft 1.12.2
Forge 2847
Star Tech modpack [v2.3.1](https://www.curseforge.com/minecraft/modpacks/star-tech/files/2809246)
NetherEx-1.12.2-2.0.15, LibraryEx-1.12.2-1.0.12, BiomesOPlenty-1.12.2-7.0.1.2441-universal

**Comment by LogicTechCorp** [comment]
This issue should reoccur less in newer versions. It may still happen occasionally as it is a side effect from how I render the block.
