### ISSUE TITLE
Missing recipe for Nether Brick Fence Gate

### ISSUE THREAD

**Issue by ghost** [LogicTechCorp/NetherEx-Archive#203]
Using NetherEx 2.0.15, there is no recipe for the Nether Brick Fence Gate, while all the extra variants do have recipes.

Minecraft 1.12.2
Forge 2847
Star Tech modpack 2.3.1
Netherex 2.0.15

**Comment by LogicTechCorp** [comment]
This issue will be fixed in the next version.
