### ISSUE TITLE
Missing texture for Bucket O' Blood

### ISSUE THREAD

**Issue by astra-midnight** [LogicTechCorp/NetherEx-Archive#209]
The texture in the bucket o' blood is missing. This is problematic because I use Tinkers Construct and it seems to override the blood provided by TiCon.

**Comment by ProsperCraft** [comment]
Same issue - 
![2020-03-08_13 01 38](https://user-images.githubusercontent.com/4427684/76170420-6d25fd80-6147-11ea-86bb-8bd6d7ca84a4.png)
![2020-03-08_13 03 53](https://user-images.githubusercontent.com/4427684/76170421-6dbe9400-6147-11ea-9325-49e92e447b0a.png)
![2020-03-08_13 06 50](https://user-images.githubusercontent.com/4427684/76170422-6e572a80-6147-11ea-8a6a-c9ac6c9b83e7.png)

This causes a crash when poured in to a casting basin-
https://github.com/SlimeKnights/TinkersConstruct/issues/3967

**Comment by LogicTechCorp** [comment]
@cybercatgurrl Could you please be more specific as to what the issue is?

**Comment by LogicTechCorp** [comment]
This issue is caused by VanillaFix. Tinkers latest version fixes what VanillaFix does.
