### ISSUE TITLE
Natura Compatibility? [1.12]

### ISSUE THREAD

**Issue by Fundryi** [LogicTechCorp/NetherEx-Archive#21]
Will u guys add some kind of compatibility? Between NetherEx and Natura? I really like both mods.
At this point, they are not working together at least for me. There are only Natura bioms/and other stuff. As soon as I disable Natura NetherEx biomes are there.

**Comment by LogicTechCorp** [comment]
There is no Natura compatibility at the moment, because they also replace the Nether with their own custom version. It works with Biomes O Plenty because they use their own custom biomes and Natura uses the default Vanilla Nether biome.

**Comment by LogicTechCorp** [comment]
NetherEx is now semi-compatible with Natura. The Tainted Soil and Heat Sand don't generate but I am looking into it.
