### ISSUE TITLE
Error while Initializing game

### ISSUE THREAD

**Issue by Buttonowo** [LogicTechCorp/NetherEx-Archive#210]
I was trying to open an edited modpack (rebirth of the night on twitch) and tried to copy all the mods and open it the forge way. it opened a first time but all times after it crashed because of library ex and nether ex. i don't know much about codes or errors but i tried to simply re-download the two mods and plug them in still getting the error, please help!  the error i got is below.

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2020-01-11 08:44:19 EST
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from NetherEx (netherex)
Caused by: java.lang.IllegalArgumentException: bound must be positive
    at java.util.Random.nextInt(Random.java:388)
    at logictechcorp.libraryex.utility.RandomHelper.getNumberInRange(RandomHelper.java:34)
    at logictechcorp.libraryex.utility.ConfigHelper.getItemStack(ConfigHelper.java:147)
    at logictechcorp.libraryex.trade.TradeStack.<init>(TradeStack.java:63)
    at logictechcorp.libraryex.trade.Trade.<init>(Trade.java:64)
    at logictechcorp.netherex.village.PigtificateTradeConfigManager.readTradeConfigs(PigtificateTradeConfigManager.java:93)
    at logictechcorp.netherex.NetherEx.onFMLInitialization(NetherEx.java:117)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1587531184 bytes (1513 MB) / 3355443200 bytes (3200 MB) up to 8589934592 bytes (8192 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2838 157 mods loaded, 156 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                                           | Version                 | Source                                                    | Signature                                |
       |:----- |:-------------------------------------------- |:----------------------- |:--------------------------------------------------------- |:---------------------------------------- |
       | LCHI  | minecraft                                    | 1.12.2                  | minecraft.jar                                             | None                                     |
       | LCHI  | mcp                                          | 9.42                    | minecraft.jar                                             | None                                     |
       | LCHI  | FML                                          | 8.0.99.99               | forge-1.12.2-14.23.5.2838.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHI  | forge                                        | 14.23.5.2838            | forge-1.12.2-14.23.5.2838.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHI  | ivtoolkit                                    | 1.3.3-1.12              | minecraft.jar                                             | None                                     |
       | LCHI  | com.elytradev.movingworld.common.asm.coremod |                         | minecraft.jar                                             | None                                     |
       | LCHI  | bnbgamingcore                                | 0.11.0                  | minecraft.jar                                             | None                                     |
       | LCHI  | foamfixcore                                  | 7.7.4                   | minecraft.jar                                             | None                                     |
       | LCHI  | futuremccore                                 | 0.1.12                  | minecraft.jar                                             | None                                     |
       | LCHI  | albedocore                                   | 0.1                     | minecraft.jar                                             | None                                     |
       | LCHI  | randompatches                                | 1.12.2-1.19.1.1         | randompatches-1.12.2-1.19.1.1.jar                         | None                                     |
       | LCHI  | itemblacklist                                | 1.4.3                   | ItemBlacklist-1.4.3.jar                                   | None                                     |
       | LCHI  | aether_legacy                                | 1.4.4                   | aether_legacy-1.12.2-v1.4.4.jar                           | None                                     |
       | LCHI  | aether_legacy_addon                          | 1.12.2-v1.2.3           | aether_continuation-1.12.2-v1.2.3.jar                     | None                                     |
       | LCHI  | albedo                                       | 1.0.0                   | albedo-1.12.2-1.1.0.jar                                   | None                                     |
       | LCHI  | biometweaker                                 | 3.2.354                 | BiomeTweaker-1.12.2-3.2.354.jar                           | bdea6e9d19f35da4858ffcc93210c6207dd590bd |
       | LCHI  | biomesoplenty                                | 7.0.1.2443              | BiomesOPlenty-1.12.2-7.0.1.2443-universal.jar             | None                                     |
       | LCHI  | craftstudioapi                               | 1.0.0                   | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar        | None                                     |
       | LCHI  | harvestcraft                                 | 1.12.2zb                | Pam's HarvestCraft 1.12.2zf.jar                           | None                                     |
       | LCHI  | ctm                                          | MC1.12.2-1.0.0.29       | CTM-MC1.12.2-1.0.0.29.jar                                 | None                                     |
       | LCHI  | baubles                                      | 1.5.2                   | Baubles-1.12-1.5.2.jar                                    | None                                     |
       | LCHI  | thaumcraft                                   | 6.1.BETA26              | Thaumcraft-1.12.2-6.1.BETA26.jar                          | None                                     |
       | LCHI  | twilightforest                               | 3.10.1013               | twilightforest-1.12.2-3.10.1013-universal.jar             | None                                     |
       | LCHI  | animania                                     | 1.7.3                   | animania-1.12.2-1.7.3.jar                                 | None                                     |
       | LCHI  | animatedrecipebutton                         | 1.2.1                   | AnimatedRecipeButton-v1.2.1-1.12.2.jar                    | 12d137bcc36051a1c2c8ea7211cfc1da1c6e9dea |
       | LCHI  | applecore                                    | 3.2.0                   | AppleCore-mc1.12.2-3.2.0.jar                              | None                                     |
       | LCHI  | crafttweaker                                 | 4.1.20                  | CraftTweaker2-1.12-4.1.20.jar                             | None                                     |
       | LCHI  | mtlib                                        | 3.0.6                   | MTLib-3.0.6.jar                                           | None                                     |
       | LCHI  | modtweaker                                   | 4.0.17                  | modtweaker-4.0.17.jar                                     | None                                     |
       | LCHI  | jei                                          | 4.15.0.291              | jei_1.12.2-4.15.0.291.jar                                 | None                                     |
       | LCHI  | mantle                                       | 1.12-1.3.3.55           | Mantle-1.12-1.3.3.55.jar                                  | None                                     |
       | LCHI  | betterwithmods                               | 1.12-2.3.20-1037        | BetterWithMods-1.12-2.3.20-1037.jar                       | None                                     |
       | LCHI  | appleskin                                    | 1.0.9                   | AppleSkin-mc1.12-1.0.9.jar                                | None                                     |
       | LCHI  | astikorcarts                                 | 1.12.2-0.1.2.7          | astikorcarts-1.12.2-0.1.2.7.jar                           | None                                     |
       | LCHI  | atop                                         | 1.5                     | ATOP-1.12.2-v.1.5.jar                                     | None                                     |
       | LCHI  | attributefix                                 | 1.0.4                   | AttributeFix-1.12.2-1.0.4.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHI  | quark                                        | r1.6-177                | Quark-r1.6-177.jar                                        | None                                     |
       | LCHI  | autoreglib                                   | 1.3-32                  | AutoRegLib-1.3-32.jar                                     | None                                     |
       | LCHI  | betteradvancements                           | 0.1.0.77                | BetterAdvancements-1.12.2-0.1.0.77.jar                    | None                                     |
       | LCHI  | betteranimalsplus                            | 8.0.0                   | betteranimalsplus-1.12.2-8.0.0.jar                        | None                                     |
       | LCHI  | bettercaves                                  | 1.12.2                  | bettercaves-1.12.2-1.6.0.jar                              | None                                     |
       | LCHI  | bettercombatmod                              | 1.5.6                   | BetterCombat-1.12.2-1.5.6.jar                             | None                                     |
       | LCHI  | betterhud                                    | 1.4.1                   | betterhud-1.12.2-1.4.1.jar                                | None                                     |
       | LCHI  | betternether                                 | 0.1.8.4                 | betternether-0.1.8.4.jar                                  | None                                     |
       | LCHI  | betterwithlib                                | ${version}              | BetterWithLib-1.12-1.5.jar                                | None                                     |
       | LCHI  | bloodmoon                                    | 1.5.3                   | Bloodmoon-MC1.12.2-1.5.3.jar                              | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHI  | bnbgaminglib                                 | 2.17.6                  | BNBGamingLib-1.12.2-2.17.6.jar                            | None                                     |
       | LCHI  | bookshelf                                    | 2.3.590                 | Bookshelf-1.12.2-2.3.590.jar                              | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHI  | bountifulbaubles                             | 0.0.1                   | Bountiful Baubles-1.12.2-0.1.4.jar                        | None                                     |
       | LCHI  | forgelin                                     | 1.8.4                   | Forgelin-1.8.4.jar                                        | None                                     |
       | LCHI  | bountiful                                    | 2.2.1                   | Bountiful-2.2.1.jar                                       | None                                     |
       | LCHI  | gamestages                                   | 2.0.117                 | GameStages-1.12.2-2.0.117.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHI  | carryon                                      | 1.12.3                  | CarryOn MC1.12.2 v1.12.3.jar                              | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
       | LCHI  | cd4017be_lib                                 | 6.4.14                  | CD4017BE_lib-1.12.2-6.4.14.1.jar                          | None                                     |
       | LCHI  | charm                                        | 1.12.2-1.3.6            | Charm-1.12.2-1.3.6.jar                                    | None                                     |
       | LCHI  | chunkpregenerator                            | 2.1                     | Chunk Pregenerator V1.12-2.2.jar                          | None                                     |
       | LCHI  | chunkanimator                                | 1.2                     | ChunkAnimator-MC1.12-1.2.jar                              | None                                     |
       | LCHI  | colouredtooltips                             | 1.0.9                   | ColouredTooltips-1.12.2-1.0.9.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHI  | coralreef                                    | 2.0                     | CoralReef-2.5-1.12.2.jar                                  | None                                     |
       | LCHI  | extendedrenderer                             | v1.0                    | coroutil-1.12.1-1.2.32.jar                                | None                                     |
       | LCHI  | coroutil                                     | 1.12.1-1.2.32           | coroutil-1.12.1-1.2.32.jar                                | None                                     |
       | LCHI  | configmod                                    | v1.0                    | coroutil-1.12.1-1.2.32.jar                                | None                                     |
       | LCHI  | ctgui                                        | 1.0.0                   | CraftTweaker2-1.12-4.1.20.jar                             | None                                     |
       | LCHI  | crafttweakerjei                              | 2.0.3                   | CraftTweaker2-1.12-4.1.20.jar                             | None                                     |
       | LCHI  | customloadingscreen                          | 1.12.2-1.4.1            | CustomLoadingScreen-1.12.2-1.4.1.jar                      | None                                     |
       | LCHI  | custommainmenu                               | 2.0.9                   | CustomMainMenu-MC1.12.2-2.0.9.jar                         | None                                     |
       | LCHI  | customspawner                                | 3.11.4                  | CustomMobSpawner-3.11.4.jar                               | None                                     |
       | LCHI  | movingworld                                  | 1.12-6.342              | movingworld-1.12-6.342-full.jar                           | None                                     |
       | LCHI  | davincisvessels                              | @DVESSELSVER@           | davincisvessels-1.12-6.340-full.jar                       | None                                     |
       | LCHI  | journeymap                                   | 1.12.2-5.5.6            | journeymap-1.12.2-5.5.6.jar                               | None                                     |
       | LCHI  | defaultoptions                               | 9.2.8                   | DefaultOptions_1.12.2-9.2.8.jar                           | None                                     |
       | LCHI  | dungeontactics                               | DT-0.16.6               | DungeonTactics-1.12.2-0.16.6.jar                          | None                                     |
       | LCHI  | sereneseasons                                | 1.2.18                  | SereneSeasons-1.12.2-1.2.18-universal.jar                 | None                                     |
       | LCHI  | orelib                                       | 3.6.0.1                 | OreLib-1.12.2-3.6.0.1.jar                                 | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHI  | dsurround                                    | 3.6.0.2                 | DynamicSurroundings-1.12.2-3.6.0.2.jar                    | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHI  | dynamictrees                                 | 1.12.2-0.9.6            | DynamicTrees-1.12.2-0.9.6.jar                             | None                                     |
       | LCHI  | dynamictreesbop                              | 1.12.2-1.4.1e           | DynamicTreesBOP-1.12.2-1.4.1e.jar                         | None                                     |
       | LCHI  | dynamictreesphc                              | 1.12.2-1.4.2            | DynamicTreesPHC-1.12.2-1.4.2.jar                          | None                                     |
       | LCHI  | endreborn                                    | 0.3.1                   | EndReborn III [0.3.1].jar                                 | None                                     |
       | LCHI  | epicsiegemod                                 | 13.165                  | EpicSiegeMod-13.165.jar                                   | None                                     |
       | LCHI  | minerva                                      | 1.0.13                  | minerva-library-1.0.13.jar                                | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
       | LCHI  | extraalchemy                                 | 0.5.2                   | extraalchemy-0.5.2.jar                                    | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
       | LCHI  | fantasticlib                                 | 1.12.2.029              | FantasticLib-1.12.2.029.jar                               | None                                     |
       | LCHI  | foamfix                                      | 0.10.9-1.12.2           | foamfix-0.10.9-1.12.2.jar                                 | None                                     |
       | LCHI  | minecraftfuture                              | 0.1.13                  | future-mc-0.1.13.jar                                      | None                                     |
       | LCHI  | fxcontrol                                    | 0.1.14                  | fxcontrol-1.12-0.1.14.jar                                 | None                                     |
       | LCHI  | geographicraft                               | 0.8.7                   | GeographiCraft-1.12-0.8.9b.jar                            | None                                     |
       | LCHI  | glaretorch                                   | 8.10                    | GlareTorch_Ver.8.11_[MC1.12](forge-1.12-14.21.1.2387).jar | None                                     |
       | LCHI  | grapplemod                                   | 1.12.2-v11.1            | grapplemod-v11.1-1.12.2.jar                               | None                                     |
       | LCHI  | hardcoredarkness                             | 2.0                     | HardcoreDarkness-MC1.12.2-2.0.jar                         | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHI  | hw_inv                                       | 1.12.1-1.1.9            | hostileworlds_invasions-1.12.1-1.1.9.jar                  | None                                     |
       | LCHI  | waila                                        | 1.8.26                  | Hwyla-1.8.26-B41_1.12.2.jar                               | None                                     |
       | LCHI  | llibrary                                     | 1.7.19                  | llibrary-1.7.19-1.12.2.jar                                | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHI  | iceandfire                                   | 1.8.3                   | iceandfire-1.8.3.jar                                      | None                                     |
       | LCHI  | ido                                          | 1.0.6                   | ido-1.12.2-1.1.0.jar                                      | None                                     |
       | LCHI  | incontrol                                    | 3.9.16                  | incontrol-1.12-3.9.16.jar                                 | None                                     |
       | LCHI  | initialinventory                             | 2.0.2                   | InitialInventory-3.0.0.jar                                | None                                     |
       | LCHI  | letmesleep                                   | 1.2.1                   | LetMeSleep-v1.2.1-1.12.2.jar                              | 12d137bcc36051a1c2c8ea7211cfc1da1c6e9dea |
       | LCHI  | dogslie                                      | 1.0.2                   | LetSleepingDogsLie-1.12.2-1.0.2.jar                       | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHI  | libraryex                                    | 1.0.12                  | LibraryEx-1.12.2-1.0.12.jar                               | None                                     |
       | LCHI  | lttweaker                                    | 1.1.14                  | LootTableTweaker-1.12.2-1.1.14.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHI  | loottweaker                                  | 0.1.3                   | LootTweaker-0.1.3+MC1.12.2.jar                            | None                                     |
       | LCHI  | mocreatures                                  | 12.0.5                  | Mo-Creatures-Mod-1.12.2.jar                               | None                                     |
       | LCHI  | mobstages                                    | 2.0.13                  | MobStages-1.12.2-2.0.13.jar                               | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHI  | mousetweaks                                  | 2.10                    | MouseTweaks-2.10-mc1.12.2.jar                             | None                                     |
       | LCHI  | mowziesmobs                                  | 1.5.4                   | mowziesmobs-1.5.4.jar                                     | None                                     |
       | LCHI  | multimine                                    | 1.6.2                   | MultiMine-1.12.2.jar                                      | None                                     |
       | LCHI  | multimob                                     | 1.0.5                   | multimob-1.0.5.jar                                        | None                                     |
       | LCHI  | neat                                         | 1.4-17                  | Neat 1.4-17.jar                                           | None                                     |
       | LCHI  | netherchest                                  | 1.1.1                   | netherchest-1.1.1.jar                                     | None                                     |
       | LCHE  | netherex                                     | 2.0.15                  | NetherEx-1.12.2-2.0.15.jar                                | None                                     |
       | LCH   | netherportalfix                              | 5.3.17                  | NetherPortalFix_1.12.1-5.3.17.jar                         | None                                     |
       | LCH   | notenoughcats                                | 1.2.1                   | NotEnoughCats-1.12.2-1.2.1.jar                            | None                                     |
       | LCH   | orespawn                                     | 3.3.1                   | OreSpawn-1.12-3.3.1.172.jar                               | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | potioncore                                   | 1.8_for_1.12.2          | PotionCore-1.8_for_1.12.2.jar                             | None                                     |
       | LCH   | prefab                                       | 1.3.0.26                | Prefab-Mod-1.12.2.jar                                     | None                                     |
       | LCH   | primitivemobs                                | 1.2.3a                  | primitivemobs-1.2.3a.jar                                  | None                                     |
       | LCH   | qualitytools                                 | 1.0.7_for_1.12.2        | QualityTools-1.0.7_for_1.12.2.jar                         | None                                     |
       | LCH   | rebind                                       | 2.7.5                   | rebind-1.12.2-2.7.5-0.jar                                 | 22cc4f45e4341b5bf2de5964a37e0165d157c9a2 |
       | LCH   | resourceloader                               | 1.5.3                   | ResourceLoader-MC1.12.1-1.5.3.jar                         | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCH   | additionalstructures                         | 2.3.1                   | Rex's-Additional-Structures-1.12.x-(v.2.3.1).jar          | None                                     |
       | LCH   | roguelike                                    | 1.8.0                   | RoguelikeDungeons-1.12.2-1.8.0.jar                        | None                                     |
       | LCH   | ruins                                        | 17.2                    | Ruins-1.12.2.jar                                          | None                                     |
       | LCH   | rustic                                       | 1.1.1                   | rustic-1.1.1.jar                                          | None                                     |
       | LCH   | rusticbopwoods                               | 1.0                     | rusticbopwoods-1.0.jar                                    | None                                     |
       | LCH   | silentlib                                    | 3.0.13                  | SilentLib-1.12.2-3.0.13+167.jar                           | None                                     |
       | LCH   | scalinghealth                                | 1.3.37                  | ScalingHealth-1.12.2-1.3.42+147.jar                       | None                                     |
       | LCH   | setbonus                                     | 1.12.2.016              | SetBonus-1.12.2.016.jar                                   | None                                     |
       | LCH   | simplecore                                   | 1.7.3.4                 | simplecore-1.12.2-1.7.3.4.jar                             | None                                     |
       | LCH   | simpleores                                   | 1.11.2.2                | simpleores-1.12.2-1.11.2.2.jar                            | None                                     |
       | LCH   | soundfilters                                 | 0.11_for_1.12           | SoundFilters-0.11_for_1.12.jar                            | None                                     |
       | LCH   | spartanweaponry                              | beta 1.3.8              | SpartanWeaponry-1.12.2-beta-1.3.8.jar                     | None                                     |
       | LCH   | spartanfire                                  | 0.07                    | spartanfire-0.07.jar                                      | None                                     |
       | LCH   | spartanshields                               | 1.5.4                   | SpartanShields-1.12.2-1.5.4.jar                           | None                                     |
       | LCH   | stg                                          | 1.12.2-1.2.3            | stg-1.12.2-1.2.3.jar                                      | None                                     |
       | LCH   | stygian                                      | 1.0.4                   | stygian-1.0.4.jar                                         | None                                     |
       | LCH   | tails                                        | 1.12-1.10.0             | Tails-1.12-1.10.0.jar                                     | None                                     |
       | LCH   | beneath                                      | 1.6.0                   | The Beneath-1.12.2-1.6.0.jar                              | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCH   | tips                                         | 1.0.7                   | Tips-1.12.2-1.0.7.jar                                     | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | torohealthmod                                | 1.12.2-11               | torohealth-1.12.2-11.jar                                  | None                                     |
       | LCH   | toroquest                                    | 1.12.2-5.3              | toroquest-1.12.2-5.3.jar                                  | None                                     |
       | LCH   | travellersbackpack                           | 1.0.20.20               | TravellersBackpack-1.12.2-1.0.20.20.jar                   | None                                     |
       | LCH   | triumph                                      | 3.19.2                  | Triumph-1.12.2-3.19.2.jar                                 | None                                     |
       | LCH   | undergroundbiomes                            | 1.3.7                   | UndergroundBiomesConstructs-1.12-1.3.7.jar                | None                                     |
       | LCH   | unloader                                     | 1.2.0                   | unloader-1.2.0.jar                                        | None                                     |
       | LCH   | vanillafix                                   | 1.0.10-SNAPSHOT         | VanillaFix-1.0.10-99.jar                                  | None                                     |
       | LCH   | dimstack                                     | 0.1.5                   | VerticalDimensionStack-1.12.2-0.1.5.jar                   | None                                     |
       | LCH   | villagenames                                 | 3.2.1                   | VillageNames-1.12.2-3.2.1.jar                             | None                                     |
       | LCH   | voidfog                                      | 1.1.3                   | Void-Fog-1.1.3.jar                                        | None                                     |
       | LCH   | wings                                        | 1.1.5                   | wings-1.1.5-1.12.2.jar                                    | None                                     |
       | LCH   | bauble_wings                                 | 1.0.0                   | wings-1.1.5-1.12.2.jar                                    | None                                     |
       | LCH   | wumpleutil                                   | 2.12.6                  | wumpleutil-1.12.2-2.12.6.jar                              | 1e57901a90acd4a3a54295b6decff5397be51a31 |
       | LCH   | zombieawareness                              | 1.12.1-1.11.16          | zombieawareness-1.12.1-1.11.16.jar                        | None                                     |
       | LCH   | snowrealmagic                                | 0.3.3                   | SnowRealMagic-0.3.3.jar                                   | None                                     |
       | LCH   | toolprogression                              | 1.12.2-1.6.9            | toolprogression-1.12.2-1.6.9.jar                          | e631d7254e451d0360d0148cb21407d5511d45e9 |
       | LCH   | hungeroverhaul                               | 1.12.2-1.3.3.jenkins148 | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar                | None                                     |
       | UD    | mobends_wings                                | 1.0.0                   | wings-1.1.5-1.12.2.jar                                    | None                                     |
  Loaded coremods (and transformers): wings (wings-1.1.5-1.12.2.jar)
                                        me.paulf.wings.server.asm.WingsRuntimePatcher
                                        me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
                                      ToolProgressionPlugin (toolprogression-core-1.12.2-1.6.9.jar)
                                        tyra314.toolprogression.core.asm.ToolProgressionClassTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      FMLPlugin (albedo-1.12.2-1.1.0.jar)
                                        elucent.albedo.asm.ASMTransformer
                                      TransformLoader (DynamicSurroundings-1.12.2-3.6.0.2.jar)
                                        
                                      LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
                                        lumien.bloodmoon.asm.ClassTransformer
                                      LoadingPlugin (BetterWithLib-1.12-1.5.jar)
                                        betterwithmods.library.core.ClassTransformer
                                      B3M_CorePlugin (B3M-1.12.2-15.jar)
                                        sedridor.B3M.core.B3M_Transformer
                                      MMFMLCorePlugin (MultiMine-1.12.2.jar)
                                        atomicstryker.multimine.common.fmlmagic.MMTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
                                        lumien.hardcoredarkness.asm.ClassTransformer
                                      ClsPlugin (CustomLoadingScreen-1.12.2-1.4.1.jar)
                                        alexiil.mc.mod.load.coremod.ClsTransformer
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      CharmLoadingPlugin (Charm-1.12.2-1.3.6.jar)
                                        svenhjol.charm.base.CharmClassTransformer
                                      ReBind Core (rebind-1.12.2-2.7.5-0.jar)
                                        austeretony.rebind.common.core.ReBindClassTransformer
                                      RandomPatches (randompatches-1.12.2-1.19.1.1.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
                                        lumien.chunkanimator.asm.ClassTransformer
                                      Vertically Stacked Dimensions ASM (VerticalDimensionStack-1.12.2-0.1.5.jar)
                                        cd4017be.dimstack.asm.ChunkPrimerTransformer
                                        cd4017be.dimstack.asm.BlockPortalTransformer
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.0.29.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.9-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      Quark Plugin (Quark-r1.6-177.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      iceandfire (iceandfire-1.8.3.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      FutureMC (future-mc-0.1.13.jar)
                                        thedarkcolour.futuremc.asm.CoreTransformer
                                      BNBGamingCore (BNBGamingCore-1.12.2-0.11.0.jar)
                                        com.bloodnbonesgaming.bnbgamingcore.core.BNBGamingCoreClassTransformer
                                      MovingWorldCore (movingworld-1.12-6.342-full.jar)
  GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 23.20.16.4973' Renderer: 'Intel(R) UHD Graphics 620'
  Suspected Mods: LibraryEx (libraryex), NetherEx (netherex)
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2838
  LWJGL: 2.9.4
  OpenGL: Intel(R) UHD Graphics 620 GL version 4.5.0 - Build 23.20.16.4973, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz

**Comment by Sninctbur** [comment]
Delete your config files. The mod did something internally which makes old configs cause this crash.

**Comment by Acgamble** [comment]
Thanks my game is working better then ever now

**Comment by LogicTechCorp** [comment]
This issue has been fixed in the latest version.
