### ISSUE TITLE
NetherEx biomes are not in the biome dictionary.

### ISSUE THREAD

**Issue by EnderiumSmith** [LogicTechCorp/NetherEx-Archive#211]
NetherEx biomes are not registered to the biome dictionary. this makes other mods unable to register their mobs to spawn in them.

**Comment by LogicTechCorp** [comment]
NetherEx biomes are registered to the biome dictionary, but they use their biome config to determine which mobs spawn in them.

**Comment by EnderiumSmith** [comment]
So mods cant add spawns to them? it needs to be done with the config?

**Comment by LogicTechCorp** [comment]
There's a bug with the configs at the moment. So, yes, you have to add them manually if they are not being added.

**Comment by LogicTechCorp** [comment]
I am closing this issue as NetherEx biomes are registered to the biome dictionary.
