### ISSUE TITLE
Crashes When Creating New World

### ISSUE THREAD

**Issue by Coleybuddy** [LogicTechCorp/NetherEx-Archive#212]
The game crashes and gives me the report below whenever I try to generate a new world. I'm using the latest version of NetherEX and Library EX. The only other mod I have installed is Optifine.

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// You're mean.

Time: 1/29/20 12:09 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.entity.EntityLiving$SpawnPlacementType.canSpawnAt(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;)Z
	at net.minecraft.world.WorldEntitySpawner.func_180267_a(WorldEntitySpawner.java:226)
	at net.minecraft.world.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:282)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:466)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:173)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:196)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 340024176 bytes (324 MB) / 570425344 bytes (544 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_C5 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature |
	|:------ |:--------- |:------------ |:----------------------------- |:--------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None      |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                 | None      |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCHIJA | forge     | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCHIJA | libraryex | 1.0.11       | LibraryEx-1.12.2-1.0.11.jar   | None      |
	| LCHIJA | netherex  | 2.0.15       | NetherEx-1.12.2-2.0.15.jar    | None      |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by LogicTechCorp** [comment]
I don't think this is a NEX issue, but try removing Optifine or updating all of the mods and Forge.
