### ISSUE TITLE
Biome o' plenty biomes don't generate

### ISSUE THREAD

**Issue by Critcop** [LogicTechCorp/NetherEx-Archive#217]
Biomes from biome o' plenty generate empty.
NetherEx version 2.1.0, LibEx version 1.1.0. Unchanged config, happens on both regular and biome o' plenty worlds.
Only mods loaded are NetherEx, BoP and dependencies.
![2020-03-14_18 17 56](https://user-images.githubusercontent.com/38040110/76687028-9a2f5000-6620-11ea-8192-1b1c47b0a955.png)
![Screenshot_1](https://user-images.githubusercontent.com/38040110/76687181-cbf4e680-6621-11ea-823f-e64dbf27c3fc.png)

**Comment by LogicTechCorp** [comment]
This issue has been fixed in the latest version.
