### ISSUE TITLE
NetherEx ticking while nether is unloaded

### ISSUE THREAD

**Issue by Reshy** [LogicTechCorp/NetherEx-Archive#220]
![image](https://user-images.githubusercontent.com/2096384/79036156-54f83280-7b7a-11ea-9f42-3245683865d2.png)

Not sure why, but it seems like parts of the mod are still taking up a not-insignificant amount of tick time despite the mod's content not being in use.

**Comment by LogicTechCorp** [comment]
That ticking isn't related to the Nether. It has to do with checking whether an entity is frozen or not and if so, it tries to randomly unfreeze them before the effect runs out. What are you using to profile the tick time so I can do some testing to try and see if I can reduce it.

**Comment by LogicTechCorp** [comment]
This issue will be fixed in the next release.
