### ISSUE TITLE
Bug with Grimorie of gaia spawns

### ISSUE THREAD

**Issue by zEpiixz** [LogicTechCorp/NetherEx-Archive#223]
So if you use grimoria of gaia and nether ex and create a flatworld the world will get flooded with mimic and vase spawns. If you remove nether ex its all fine. Im not sure on which side the bug happens so i report it on both tickets. Just ignore it if you are sure its not from your side.

**Comment by LogicTechCorp** [comment]
I am unable to reproduce this issue.

**Comment by zEpiixz** [comment]
Seems fixed with the latest version of NetherEX
