### ISSUE TITLE
[1.12] NetherEx + Avaritia hoe OR Draconic Evolution's Draconic hoe with land fill activated = Crash

### ISSUE THREAD

**Issue by Creerio** [LogicTechCorp/NetherEx-Archive#225]
> ### Minecraft Informations

Launcher used : MultiMC V0.6.11 (latest) + Official launcher

Minecraft version : 1.12.2 with Forge 14.23.5.2854 (latest)

Mod versions : Latest found on curseforge.

> ### Summary of the issue

Using the hoe of the green earth from Avaritia with NetherEx installed makes the game crash.

Same issue with the draconic hoe with the land fill option activated.

Removing NetherEx seems to fix the problem.

> ### How to reproduce it

**Step 1** : Take the needed mods (NetherEx + Avaritia + Draconic Evolution) into any kind of 1.12 minecraft instance with the latest forge version installed (14.23.5.2854 as of now)

**Step 2** : Create any kind of world or join a server with those mods

**Step 3** : Take the hoe of the green earth or the draconic hoe (you need to activate the land fill option, maybe change the radius too) and try to use it on dirt or grass

> ### Crash reports

**Avaritia** :

[With other mods](https://hastebin.com/biyadodogo.xml)

[Avaritia, NetherEx + Dependencies](https://hastebin.com/wiwepuzezi.cs)

[On the official minecraft launcher](https://hastebin.com/zaroqawoci.rb)

**Draconic Evolution** :

[Draconic Evolution + NetherEx](https://hastebin.com/nadecuvego.rb)

(You also have the original files under this message if hastebin has some issues)
[Official Launcher - crash-2020-04-21_11.30.49-client.txt](https://github.com/LogicTechCorp/NetherEx/files/4509069/Official.Launcher.-.crash-2020-04-21_11.30.49-client.txt)
[Avaritia + NetherEX - crash-2020-04-21_10.45.23-client.txt](https://github.com/LogicTechCorp/NetherEx/files/4509070/Avaritia.%2B.NetherEX.-.crash-2020-04-21_10.45.23-client.txt)
[Other Mods - crash-2020-04-21_10.30.42-client.txt](https://github.com/LogicTechCorp/NetherEx/files/4509072/Other.Mods.-.crash-2020-04-21_10.30.42-client.txt)
[Draconic + NetherEx - crash-2020-04-21_11.54.15-client.txt](https://github.com/LogicTechCorp/NetherEx/files/4509205/Draconic.%2B.NetherEx.-.crash-2020-04-21_11.54.15-client.txt)

> ### Suspected cause

With what I found, I think it's because NetherEx handles something with blocks although I don't know how this mod works so.. not totally sure if that's the reason.

> ### Additional information

This issue is only reported here (for now), if you need me to report it on the other mods GitHub just tell me and I'll do it.

**Comment by LogicTechCorp** [comment]
This issue will be fixed in the next release.
