### ISSUE TITLE
Crash when generating world with YUNG's better caves (1.12)

### ISSUE THREAD

**Issue by MrProton657** [LogicTechCorp/NetherEx-Archive#229]
crash report: https://pastebin.com/bRkKCPQC
Nether EX version: I tried differend ones, the newest (2.1.5), and some previous ones

**Comment by LogicTechCorp** [comment]
I did not encounter a crash when using the latest versions of LibraryEx, NetherEx, and YUNG's Better Caves. If you do encounter a crash when using the latest versions of the mods, send me that crash report.

**Comment by MrProton657** [comment]
I Had a crash while generating a world, then I deleted NetherEX, and after some time I added the same Version, and it works idk why

**Comment by MrProton657** [comment]
I think I forgot to include LibaryEX in my modpack then, now I added it too, so this is why
