### ISSUE TITLE
(1.12.2) - Enderdragon Fireball Mist Particles are rendered invisible

### ISSUE THREAD

**Issue by Ghostrider231** [LogicTechCorp/NetherEx-Archive#231]
NetherEx Version: 1.12.2-2.1.5
LibEx Version: 1.12.2-1.1.2

Hello,

I don't know if 1.12 is being looked at anymore, but I'll post this anyways.

I've noticed that the Ender dragon's fireball misty poison particles are not rendered, essentially making them invisible, and yes it can still hurt anyone inside it.

With some testing, the issue brought me all the way down to this mod alone.

--------

How to reproduce:

**(Vanilla, but harder method)**
1. Make sure you are in creative mode.
2. use the command: /fill ~ ~ ~ ~ ~ ~ end_portal
3. You will be warped into the end.
4. Go somewhere out in the open.
5. Change to survival mode so that the ender dragon can shoot fireballs at you.
6. When the fireball hits you or the ground, the purple mistly particles won't be rendered.

**(OR Using a magic mod that adds the dragon fireball, I use EB Wizardry because it has the dragon fireball spell)**
1. Make sure you are in creative mode.
2. Go in the creative tab and search "Dragon fireball" and you'll see a scroll
3. Get the scroll and have it held on hand.
4. Look at the ground and right click the dragon fireball scroll.
5. When the fireball hits the ground or anybody the purple misty particles won't be rendered.

**Comment by LogicTechCorp** [comment]
This issue will be fixed in the next version.
