### ISSUE TITLE
(1.12.2) Lingering Potions no longer emit lingering clouds or give out effects

### ISSUE THREAD

**Issue by Ghostrider231** [LogicTechCorp/NetherEx-Archive#235]
NetherEx Version: 1.12.2-2.1.7
LibEx Version: 1.12.2-1.1.3

Lingering Potions no longer emit lingering clouds or give anyone its effects at all.

It doesn't even emit the clouds either, just nothing.

This only applies to lingering potions. Creepers themselves can still emit lingering clouds and everything, but not lingering potions.

And yes, I only have this mod and the lib mod installed, nothing else.

How to reproduce:
--------------------------
1. Start any world, new or not.
2. Get any Lingering Potion (creative mode or not)
3. Have the lingering potion selected on hand and right click to throw.
4. Once the lingering potion hits something, it should be emitting clouds, **but it doesn't**. Essentially means you cannot receive its effects. (effectively making them useless)

**Comment by LogicTechCorp** [comment]
I'll take a look when I can.

**Comment by LogicTechCorp** [comment]
This issue will be fixed in the next version.
