### ISSUE TITLE
LootTable Error

### ISSUE THREAD

**Issue by Zarpyk** [LogicTechCorp/NetherEx-Archive#236]
When a player enter nether, the server kick the player
"Crash" log: https://gist.github.com/GuerreroCraft61/15b6eb38a938787b5cb77288e6cdb14d

**Comment by Zarpyk** [comment]
Other log: https://gist.github.com/GuerreroCraft61/6352971e8c2a45366c2f51d34ac45581

**Comment by LogicTechCorp** [comment]
I know where the issue is, I'll fix it when I have time.

**Comment by LogicTechCorp** [comment]
This issue will be fixed in the next release.
