### ISSUE TITLE
Missing recipies for smelting netherrack bricks

### ISSUE THREAD

**Issue by tprk77** [LogicTechCorp/NetherEx-Archive#237]
Version: 1.14.4, 3.0.3

I'm guessing that it should be possible to smelt the various types of netherrack into their corresponding bricks. But unfortunately this seems to not be working.

I'm fairly new to Minecraft modding, but I might be able to do the work to add the recipes. Would you accept a PR for that?

**Comment by LogicTechCorp** [comment]
You are correct. I would accept a PR, but there are other bugs I need to fix, so I don't mind adding it to my to do list.

**Comment by LogicTechCorp** [comment]
This will be fixed in the next release.
