### ISSUE TITLE
Make every recipes including Wither Bones accept <ore:boneWithered>

### ISSUE THREAD

**Issue by ChromaPIE** [LogicTechCorp/NetherEx-Archive#239]
Some other mods like Tinker's Construct also have Wither Bone included and it also has the OreDict <ore:boneWithered>, and maybe it should be able to make equipments in NetherEx too.

**Comment by LogicTechCorp** [comment]
This will be implemented in the next version. I will also be sure to add support for other amethyst blocks and items.
