### ISSUE TITLE
Incompatibility with Buildcraft

### ISSUE THREAD

**Issue by cursinorock** [LogicTechCorp/NetherEx-Archive#24]
Incompatibility with Buildcraft, laucher crash.
Version 1.11.2
[crash-2017-07-08_19.39.55-client.txt](https://github.com/LogicTechCorp/NetherEx/files/1133365/crash-2017-07-08_19.39.55-client.txt)

**Comment by LogicTechCorp** [comment]
This issue has been fixed in the latest version.
