### ISSUE TITLE
[1.12.2] NetherEx Mobs Ignore Player Distance Check When Spawning

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [LogicTechCorp/NetherEx-Archive#240]
According to one of my beta testers for my modpack, NetherEx mobs seem to ignore player distance check on spawn and tend to spawn right on top of the player. Given quite extreme spawn rate this is absolutely deadly without endgame gear and enchants. And endgame isn't reachable without visits to Nether.

Forge: forge-1.12.2-14.23.5.2847-universal
Tested With: NetherEx-1.12.2-2.1.7.jar

**Comment by PiggiesGoSqueal** [comment]
He now says:
"I am struggling to reproduce that behavior to be honest, its possible i was just at the wrong spot and had mobs falling from above me, a top of my head. Had seen it twice and decided to post here, but as of now I'm not sure its a real thing ;/"

So feedback would be appreciated if you could confirm the behavior of the mod is properly setup to avoid this issue. Thanks!

**Comment by LogicTechCorp** [comment]
I don't spawn mobs any differently than vanilla, so it could have been a one off issue. I am going to close this, but I can reopen it if the issue reoccurs.
