### ISSUE TITLE
Can't repair Amedian Tools

### ISSUE THREAD

**Issue by CovertJaguar** [LogicTechCorp/NetherEx-Archive#241]
The code suggests that Nether Amethyst Crystals should repair them, but it doesn't seem to work.

If I had to guess, I'd say that the Tool Material is being initialized with a null item before AMETHYST_CRYSTAL is initialized.

Version: 1.12.2-2.1.7

**Comment by LogicTechCorp** [comment]
I'll take a look soon and update the issue when the fix is available.

**Comment by LogicTechCorp** [comment]
This issue has been fixed in the latest version.
