### ISSUE TITLE
Gloomy Nether Brick not registered

### ISSUE THREAD

**Issue by StellaBiscuit** [LogicTechCorp/NetherEx-Archive#242]
With 1.15.2 (4.0.0), the game crash at start with the error "java.lang.NullPointerException: Registry Object not present: netherex:spore_creeper_explosion"

Crash Report VVV
[crash-2020-07-29_11.17.18-client.txt](https://github.com/LogicTechCorp/NetherEx/files/4995702/crash-2020-07-29_11.17.18-client.txt)

Log VVV
[latest.log](https://github.com/LogicTechCorp/NetherEx/files/4995704/latest.log)

**Comment by StellaBiscuit** [comment]
Waaaaait on twitch it downloaded 1.14 version on Twitch O.o

**Comment by TBiscuit1** [comment]
oops missclick

**Comment by StellaBiscuit** [comment]
God, new error, now it's the gloomy netherbrick that does the error
Mod installed : 
AutoRegLib
Better Advancement
Bottle Your XP
Cherished Worlds (Forge)
Collective
_ContentTweaker_
_CraftTweaker_
Cucumber Library
Cyclic
Forgiving Void
Inital Inventory
Inventory Generator
Iron Jetpacks
_JEITweaker_
JEI
_LibraryEx_
MouseTweaks
_NetherEx_
Portable Crafter (Forge)
Quark
ReAuth

Edit : You only need some mods not all to produce the crash (The mods are the italic ones)

**Comment by LogicTechCorp** [comment]
Closing as it was discussed on discord that using the latest version of CraftTweaker fixed the issue.
