### ISSUE TITLE
Weird Terrain Generation 

### ISSUE THREAD

**Issue by rhgngle** [LogicTechCorp/NetherEx-Archive#244]
Forge Ver: 14.23.5.2854
Mods Installed: 
BiomesOPlenty 7.0.1.2444
LibraryEx 1.1.3
NetherEx 2.1.8

Pics are taken in a BoP world but non BoP worlds also have this issue

![2020-08-03_21 33 06](https://user-images.githubusercontent.com/63624574/89188836-c51b4000-d5d1-11ea-8f74-2c327e3c5ccd.png)
![2020-08-03_21 33 48](https://user-images.githubusercontent.com/63624574/89188841-c77d9a00-d5d1-11ea-8cff-1e714970b673.png)
![2020-08-03_21 34 31](https://user-images.githubusercontent.com/63624574/89188847-c8163080-d5d1-11ea-97a4-b96b1ccd1e75.png)
![2020-08-03_21 55 53](https://user-images.githubusercontent.com/63624574/89190540-32c86b80-d5d4-11ea-8634-ccd38ae824cd.png)
![2020-08-03_21 55 50](https://user-images.githubusercontent.com/63624574/89190546-34922f00-d5d4-11ea-9b84-c2f6c96a04e4.png)

It does not happen everywhere but is still annoying to look at. This does not seem to affect biomes themselves at all, as only the generation is affected. They are along chunk boundaries. Affected chunks usually have either pure netherrack or blocks from other biomes. Only BoP biomes seem to be affected. Decorations do not get overwritten.
Top 2 Pics: Phantasmagoric Inferno and Corrupted Sands overwritten, near some Ruthless Sands
Middle Pic: Undergarden overwritten by Visceral Heap generation
Bottom 2 Pics : BoP Fungi Forest overwritten, near a Torrid Wasteland

**Comment by LogicTechCorp** [comment]
I'll take a look sometime soon. Do you have the world seed?

**Comment by rhgngle** [comment]
No, I deleted the instance after that

**Comment by Librv** [comment]
Having the same issue here, happens in any nether that you generate while having both bop and netherex installed
![2020-10-18_12 20 36](https://user-images.githubusercontent.com/73041325/96364754-6713e880-113c-11eb-9f73-1a8f0882e99f.png)

There is basically no issue in bop and netherex biomes merging, but between bop biomes you get these "biome squares", as if bop was overlapping its own generation. This does not happen when netherex is removed.

**Comment by LogicTechCorp** [comment]
This issue has been fixed in the latest version.
