### ISSUE TITLE
Missing features on 1.15.2

### ISSUE THREAD

**Issue by L-Aleixo** [LogicTechCorp/NetherEx-Archive#245]
I downloaded this mod after watching some videos about it on 1.12 so I installed it on my 1.15.2 game and noticed some features missing. I couldn't find the Pigtificates, Ghastling or Brute's Egg Spawners on creative, couldn't make a gold golem and couldn't find any of them or the dungeons anounced while flying around the nether for quite a while...

Did I do something very wrong while installing or they got removed?

**Comment by LogicTechCorp** [comment]
The structures were removed in later 1.12 versions and some mobs and items were removed in the 1.14 update.
