### ISSUE TITLE
Weird Issue

### ISSUE THREAD

**Issue by janagyjr** [LogicTechCorp/NetherEx-Archive#247]
Upon building a nether portal, I found myself in an area of lively netherrack and the associated stuff. Also, my base became regularly overrun with zombie pigmen, like hundreds of them. I had to break the portal on my end. Is this a known issue?

![2020-08-04_00 32 17](https://user-images.githubusercontent.com/23646259/89743037-d6ab8e80-da8e-11ea-926e-ff3c8af6e485.png)
![2020-08-04_00 32 23](https://user-images.githubusercontent.com/23646259/89743038-d90de880-da8e-11ea-9a80-c72dc04c64e0.png)
![2020-08-04_00 32 35](https://user-images.githubusercontent.com/23646259/89743041-d9a67f00-da8e-11ea-9402-216193975e32.png)

**Comment by janagyjr** [comment]
NetherEx version 2.1.8
MC 1.12.2
Forge 14.23.5.2854
Modpack: TCG's Just for Fun

**Comment by LogicTechCorp** [comment]
Were you using NetherEx's nether portal or the Vanilla nether portal?

**Comment by LogicTechCorp** [comment]
Closing this issue as I could not replicate it.
