### ISSUE TITLE
All instances of Ichor are replaced with Blood from Tinker's Construct (1.12.2)

### ISSUE THREAD

**Issue by AlasICannotSwim** [LogicTechCorp/NetherEx-Archive#249]
Nether EX version:  1.12.2-2.1.8

Naturally-generated pools of Ichor in the Nether are made of Blood from Tinker's Construct instead. 

When attempting to place Ichor in the world, WAILA shows it as Blood from Tinker's Construct, and picking it up with a bucket gives a Bucket o' Blood. 

However, while placing a Bucket o' Blood in the Nether causes it to evaporate like water (as it's presumably supposed to), placing Ichor in the Nether does not evaporate, even though it's supposedly also Blood?

Also, not sure if this is related, but buckets of Ichor do not exist in JEI or the creative inventory; only the square fluid texture can be found. Using tab-autocomplete for the /give command doesn't show any Ichor Buckets either. 

The attached log has me loading a fresh world, going to the Nether, finding what should be a pool of Ichor (only it's blood), messing around with it, and spawning in what should be actual Ichor (only it places as Blood). 

[latest.log](https://github.com/LogicTechCorp/NetherEx/files/5087527/latest.log)

Edit: Upon further experimentation, it seems Ichor also cannot be placed in any kind of tank (Open Blocks, EnderIO, etc.).

**Comment by LogicTechCorp** [comment]
This issue has been fixed in the latest version.
