### ISSUE TITLE
Crash with CoFH Core installed 1.11.2

### ISSUE THREAD

**Issue by kragnoth** [LogicTechCorp/NetherEx-Archive#25]
CoFH core version: 1.11.2-4.2.6.13
NetherEx version: 1.1.2.3

Believe its a conflict with the dynamically generated fluids from CoFH core that are used by thermal foundation/expansion/dynamics.

Github link: https://pastebin.com/YRitvuw3  (this thing gets exponentially larger if I leave it running)

**Comment by LogicTechCorp** [comment]
This issue has been fixed with the latest version.
