### ISSUE TITLE
Minecraft crashes during forge loading sequence

### ISSUE THREAD

**Issue by DaddyGunXTC** [LogicTechCorp/NetherEx-Archive#250]
I am currently trying to play my own mod pack (89 total), and I can't even get to the Minecraft screen because every time during the forge mod loading sequence It crashes. Now, what I can tell from the crash log is that my issue probably has something to do with Advent of Ascension 3 (file name AoA3-3.3.3.jar). I believe this from this line in the report:
java.lang.NoClassDefFoundError: net/tslat/aoa3/entity/boss/horon/EntityHoron

If anyone can please explain how to fix this I will be eternally grateful as this is my first attempt of making my own mod pack. I am using the twitch app to download and set up this back FYI and I will also attach the full crash log.
One last thing, if I am on the wrong help page I ask for someone to point me in the right direction.

Thanks,
Sincerely, DaddyGunXTC

[crash-2020-08-20_23.38.15-client copy.txt](https://github.com/LogicTechCorp/NetherEx/files/5106718/crash-2020-08-20_23.38.15-client.copy.txt)

**Comment by LogicTechCorp** [comment]
This issue is not related to NetherEx, but I tried to take a look into it and I couldn't find the cause. It'd be best to ask on the Advent of Ascension GitHub [here](https://github.com/Tslat/Advent-Of-Ascension/issues).
