### ISSUE TITLE
[1.15.2] Mogus and Salamander names are not displayed correctly

### ISSUE THREAD

**Issue by TheUntamed** [LogicTechCorp/NetherEx-Archive#252]
Title and screenshot should explain it. The other mobs (including the mobs of this mod) are displayed correctly
![Screenshot_2](https://user-images.githubusercontent.com/48363903/91566762-6af96a80-e944-11ea-91f0-f16b6dbfacc1.jpg)

NetherEx-1.15.2-4.0.0
forge-31.2.36

**Comment by LogicTechCorp** [comment]
This issue has been fixed in the latest version.
