### ISSUE TITLE
[1.12.2] Pigtificate trades can't be edited 

### ISSUE THREAD

**Issue by CalaMariGold** [LogicTechCorp/NetherEx-Archive#259]
Using the Copy mod to edit the pigtificate trades. Really strange thing going on where most entries that I add in work, but can't seem to remove their default trades no matter what I try. Changing the items in entries doesn't work either, it just defaults back to their regular trade. Seems like its only working when I add a completely new trade.

**Comment by LogicTechCorp** [comment]
I am currently working on a bug fix update and will add this to my to do list.

**Comment by LogicTechCorp** [comment]
This issue has been fixed in the latest version. I've also fixed the issue where enchanted books aren't assigned an enchantment.
