### ISSUE TITLE
Crash upon world load/generation [1.12]

### ISSUE THREAD

**Issue by BBoldt** [LogicTechCorp/NetherEx-Archive#26]
https://gist.github.com/5a1da5f1e278f25675d2aa383778d41a

**Comment by LogicTechCorp** [comment]
Are you loading it in a brand new world or an old world?

**Comment by BBoldt** [comment]
Same result for both.

**Comment by BBoldt** [comment]
It must be a mod interaction, I can load the mod fine with just Forge.

**Comment by BBoldt** [comment]
Strangely the issue seems to have resolved itself.

I removed the mod, updated forge 2410 -> 2412, readded the mod, and now everything works.

**Comment by Mattabase** [comment]
This issue is happening in 1.11 as well.

That said I am using other mods. 

https://goo.gl/6Mq7WU

**Comment by LogicTechCorp** [comment]
This issue should be fixed in the latest version.
