### ISSUE TITLE
Nether Ex icy_netherrack caused a crash 

### ISSUE THREAD

**Issue by BunE-exe** [LogicTechCorp/NetherEx-Archive#261]
After mining icy_netherrack underneath a villager outpost. From what I suspect caused Minecraft to use large amounts of ram. But here the crash log.

[crash-2020-11-24_22.07.42-client.txt](https://github.com/LogicTechCorp/NetherEx/files/5590698/crash-2020-11-24_22.07.42-client.txt)

**Comment by LogicTechCorp** [comment]
This issue is not caused by NetherEx. Minecraft just simply ran out of memory and the Icy Netherrack item entity is the last thing that was ticked.
