### ISSUE TITLE
NetherEX Spawn issues Serverside (1.12.2)

### ISSUE THREAD

**Issue by shanzenos** [LogicTechCorp/NetherEx-Archive#264]
I have a strange issue I've been having with nether-ex where singleplayer, it works fine- but multiplayer the only nether mobs that spawn, spawn at nether fortresses and no nether-ex mobs spawn at all. Neither do the nether-ex biomes spawn either. This bug also prevents not only vanilla spawn outside nether fortresses, but also prevents other mods from spawning any mobs in the nether. This all works completely fine offline/singleplayer however though. This results in an almost entirely empty nether.

Should mention I run mohist as my server software (as I know it is temperamental with some mods)

Mods running that affect the nether generation:
https://www.curseforge.com/minecraft/mc-mods/future-minecraft
https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty
And Nether EX.

**Comment by LogicTechCorp** [comment]
It is caused by an issue with the server software. I am not sure why, but NetherEx doesn't work with some hybrid server software.

**Comment by DanyGames2014** [comment]
I dont know if this can be revived but this issue is happening with forge 2847 too, removing "world/config/netherex/nether_biomes/*" seems to fix the issue, or atleast some mobs start spawning

**Comment by Irgendwer01** [comment]
@LogicTechCorp (I know this is a bit late) Actually, NetherEX is the only mod that can't generate it's biomes on Mohist in the Nether, others like Biomes O' Plenty work just fine.

**Comment by LogicTechCorp** [comment]
Mohist was made aware of the issue, but they haven't fixed it yet. Try removing -1 from the "autounloadWorld_whitelist" section in the Mohist config and see if it fixes the issue.

**Comment by Irgendwer01** [comment]
@LogicTechCorp The option is standard off, I already tried that lol
