### ISSUE TITLE
Issue with spinouts

### ISSUE THREAD

**Issue by shanzenos** [LogicTechCorp/NetherEx-Archive#265]
Testing the mobs in single player I noticed the only thing that doesn't work is the spinout. The mob does not move anymore how it is supposed to (going off videos), does not attack, and is not aggressive to anything. The blades on it also no longer deal damage for some reason.

**Comment by LogicTechCorp** [comment]
Which version of the mod and what other mods are installed?

**Comment by aks746** [comment]
I had the same problem in a large modpack. After some tests, I found an incompatibility between these mods:

**astikorcarts-1.12.2-0.1.2.7.jar**
LibraryEx-1.12.2-1.2.2.jar
NetherEx-1.12.2-2.2.5.jar

Without AstikorCarts mod Spinouts works correctly.
