### ISSUE TITLE
[1.12.2] NetherEX features not generated properly in DIM-1 on Multiplayer game

### ISSUE THREAD

**Issue by RisingInIris2017** [LogicTechCorp/NetherEx-Archive#267]
#### Mod version:
LibraryEx-1.12.2-1.1.3
NetherEx-1.12.2-2.2.2

#### Forge version:
14.23.5.2854

#### Singleplayer or Multiplayer:
Multiplayer, using the [Mohist-Community/Mohist](https://github.com/Mohist-Community/Mohist) Minecraft server platform.

#### Installed mods:
Only LibraryEx-1.12.2-1.1.3 and NetherEx-1.12.2-2.2.2 are installed on the server side.

## Description of the problem
After server is started, and it finishes generating the Nether (DIM-1), use
`forge setdim <PlayerID> -1`
command to enter the nether.

Then we will find that the nether has no NetherEX features. No mobs, no structures, no Urns of Sorrow.

However, NetherEX works perfectly on Singleplayer games.

I have reported the same issue to [Mohist-Community/Mohist](https://github.com/Mohist-Community/Mohist) Minecraft server platform's GitHub repo. If you think that this issue is not related to your NetherEX mod, but a server platform issue, please tell me and I will further contact with devs of Mohist.

I greatly appreciate for your kind help in advance.
Thanks a lot!

**Comment by LogicTechCorp** [comment]
I believe this issue is caused by the server software.
