### ISSUE TITLE
BBOP compatibility issue

### ISSUE THREAD

**Issue by Glassimo-1** [LogicTechCorp/NetherEx-Archive#268]
This is with NetherEx-1.12.2-2.2.2.jar and OpenTerrainGenerator-1.12.2-v9.3.jar.

I want to add this mod to my modpack which heavily relies on open terrain generator with the biome bundle o plenty preset. Compatibility with BOP is fine by itself but when generating a world with OTG the BOP nether biomes don´t generate with netherex installed(log says it uses default worldtype). Some wisdom on this would be great.

**Comment by LogicTechCorp** [comment]
This issue has been fixed in the latest version.
