### ISSUE TITLE
[1.12.2] BOP Nether Biomes not generating in RTG Worldtype

### ISSUE THREAD

**Issue by gimmevidya** [LogicTechCorp/NetherEx-Archive#269]
**Mod version:**
LibraryEx-1.12.2-1.2.1
NetherEx-1.12.2-2.2.3

**Forge version:**
14.23.5.2854

**Installed mods:**
BiomesOPlenty-1.12.2-7.0.1.2443
RTG-1.12.2-6.1.0.0
GeographiCraft-1.12-0.8.9b

**Description of the problem:**

When RTG Worldtype is selected, Biomes O Plenty Nether biomes do not generate in the created nether.
Nether generation includes NetherEx and Biomes O Plenty biomes as expected in default or Biomes O Plenty worldtypes

May be related to issue #268

**Comment by LogicTechCorp** [comment]
This issue has been fixed in the latest version.
