### ISSUE TITLE
Pigtificate villages not spawning / too rare. 

### ISSUE THREAD

**Issue by gregorycherry** [LogicTechCorp/NetherEx-Archive#272]
Please can you make a config that allows pig villages to spawn in more biomes / controls the the spawn rarity of villages. Thank you!

**Comment by LogicTechCorp** [comment]
You need to edit the biome json configs which are located in your world save config folder (if "usePerWorldBiomeConfigs" is true) and/or your global config folder (if "useGlobalBiomeConfigs" is true). 

You need to edit this block in the default nether biome json config or add it to the "traits" section in the other biome configs:
```
{
	"generationAttempts": 1,
	"generationStage": "structure",
	"generationProbability": 0.25,
	"structureType": "ground",
	"minimumGenerationHeight": 32,
	"clearancePercentage": 0.75,
	"randomizeGenerationAttempts": false,
	"structures": [
		"netherex:pigtificate_village/tiny_pigtificate_village"
	],
	"trait": "libraryex:structure",
	"maximumGenerationHeight": 118,
	"ignoredBlock": {
		"block": "minecraft:structure_void"
	}
}
```
The main values you need to edit are the "generationAttempts" and "generationProbability" values. If either value is set too high the villages may spawn inside each other.
