### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Exzept1on** [LogicTechCorp/NetherEx-Archive#274]
How to disable netherex ore gen?

**Comment by LogicTechCorp** [comment]
You need to edit the biome json configs. For 1.12, they are located in your world save config folder (if "usePerWorldBiomeConfigs" is true) and/or your global config folder (if  "useGlobalBiomeConfigs" is true). For 1.14/1.15, you need to create a datapack with the ore gen config sections removed.

In 1.12, the sections you need to remove are located under the "traits" section and look similar to this:
```
{
	"generationAttempts": 16,
	"generationStage": "ore",
	"generationProbability": 1.0,
	"minimumGenerationHeight": 10,
	"veinSize": 14,
	"blockToSpawn": {
		"block": "netherex:quartz_ore"
	},
	"randomizeGenerationAttempts": false,
	"blockToReplace": {
		"block": "netherex:icy_netherrack"
	},
	"trait": "libraryex:ore",
	"maximumGenerationHeight": 108
}
```

In 1.14/1.15, the sections you need to remove are located under the "features" section and look similar to this:
```
{
        "feature": {
            "name": "minecraft:ore",
            "config": {
                "state": {
                    "Name": "netherex:quartz_ore"
                },
                "target": "netherrack_tag",
                "size": 14
            }
        },
        "decorator": {
            "name": "minecraft:count_range",
            "config": {
                "count": 8,
                "bottom_offset": 10,
                "top_offset": 30,
                "maximum": 128
            }
        },
        "stage": "underground_ores"
}
```
To create your own datapacks you can look at the 1.14 datapacks here: https://github.com/LogicTechCorp/NetherEx/tree/7efd60638856a79ca7baa351365ad55a1587615e/src/main/resources/datapacks and the 1.15 datapacks here: https://github.com/LogicTechCorp/NetherEx/tree/4b7b2faf73f098341b063741f2e30773b9a459c9/src/main/resources/datapacks.

**Comment by SpeeeDCraft** [comment]
Thanks. Where can I find the "useGlobalBiomeConfigs" parameter on 1.12.2

**Comment by Exzept1on** [comment]
@LogicTechCorp Thanks :)
