### ISSUE TITLE
Server crashes NetherEX is included in the mods

### ISSUE THREAD

**Issue by Mellohi138** [LogicTechCorp/NetherEx-Archive#276]
I tried to run NetherEX & LibraryEX on a server and the it crashed when trying to start up the server. I'm using the latest forge version, and I'm also using the latest version of both of the mods and there were no config changes made to any of them.

Crash Report: https://pastebin.com/vyc8NZ28
Log File: https://pastebin.com/M9xtxJQH
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2855

NetherEX Version: 2.2.4
LibraryEX Version: 1.2.1

**Comment by LogicTechCorp** [comment]
Try the latest version I just released and see if it fixes your issue.

**Comment by Mellohi138** [comment]
Alright, it worked! Thank you for the fix!
