### ISSUE TITLE
Will Structures be added back?

### ISSUE THREAD

**Issue by Spongecade** [LogicTechCorp/NetherEx-Archive#277]
I remember you saying you planned on adding structures back but in a different (better) way... #121
Do you still plan on adding structures back?

**Comment by LogicTechCorp** [comment]
There are no current plans to add any new or removed content to NetherEx. NetherEx is feature complete and will no longer be updated aside from bug fixes. A successor mod is being worked on which will replace NetherEx in future Minecraft versions.

**Comment by Spongecade** [comment]
Ok
