### ISSUE TITLE
Wither/Frost/Blazing Sword not applying any effects

### ISSUE THREAD

**Issue by DDJJCCMM** [LogicTechCorp/NetherEx-Archive#278]
The Wither sword doesn't apply the Wither effect. Is it meant to? Given that it has quite  low damage, I would assume that is to balance the intended wither effect.

Using most recent versions of NetherEx and LibraryEx for 1.12.2.

**Comment by LogicTechCorp** [comment]
The swords in NetherEx aren't meant to apply any effects. They are meant to do stone sword level damage, but have higher uses, efficiency, and enchantability than a diamond sword.
