### ISSUE TITLE
Spawners have pigs in them

### ISSUE THREAD

**Issue by Helpbot3000** [LogicTechCorp/NetherEx-Archive#28]
The spawners I have come across all have pigs inside them instead of the mob they are actually spawning.

**Comment by LogicTechCorp** [comment]
If I understand you correctly, the spawners still spawn their mobs but the mob inside the spawner is a pig?

**Comment by Helpbot3000** [comment]
Correct.

**Comment by 63502** [comment]
I will also mention that the spawner itself shows up in Hwyla as a pig spawner.

**Comment by LogicTechCorp** [comment]
This issue should be fixed in the latest release.
