### ISSUE TITLE
Allow Distrobution outside of curseforge

### ISSUE THREAD

**Issue by Merith-TK** [LogicTechCorp/NetherEx-Archive#283]
![image](https://user-images.githubusercontent.com/10422110/176382891-7f637e08-cb25-4830-bf8b-2a7de8518ceb.png)

please just flick this switch, this allows third party launchers such as PolyMC using Packwiz, to download the mod, and not restrict us to only curseforge launcher

**Comment by Anthonity** [comment]
good

**Comment by LogicTechCorp** [comment]
Done.
