### ISSUE TITLE
1.12 Netherwart not growing anymore

### ISSUE THREAD

**Issue by Knito58** [LogicTechCorp/NetherEx-Archive#32]
Have a strange issue with netherwart which doesn't grow anymore. Its stuck at 0% growth for minecraft days and weeks. This happens in all dimensions and not only in SSP, but also in creative mode.

I tried to figure out which mod to blame and finally found my netherwart growing again when NetherEx was disabled in the mods folder (renamed to *.txt).

Data:

MC 1.12
Forge 14.21.1.2420
NetherEx 2.1.8.9

**Comment by Knito58** [comment]
Went back to version 2.1.4.5 and it was in all of those versions. Didn't have NetherEx earlier so I cannot tell anything about oder versions.

**Comment by LogicTechCorp** [comment]
It now grows similar to Wheat. It needs to be planted on Tilled Soul Sand and it requires a block of Ichor to hydrate the Tilled Soul Sand. You till the Soul Sand with a Golden Bone Hoe and the Ichor can be found in the Arctic Abyss biome. You can disable this in the config to use the default Vanilla growth.

**Comment by Knito58** [comment]
Ah silly me. My reading allergy. Thanks for enlighting me.
