### ISSUE TITLE
1.12 - Crash on startup

### ISSUE THREAD

**Issue by Seth0067** [LogicTechCorp/NetherEx-Archive#36]
[Paste](https://pastebin.com/9qVZZGVU)

LMK if you need any more info!

**Comment by LogicTechCorp** [comment]
I tested to see if NetherEx loads fine on its own and it does. This issue must be caused by an interaction with another mod. If you remove NetherEx does Minecraft load without any other issues?

**Comment by Seth0067** [comment]
Hi LTC - yes you are correct, this was another mod (I think Malisis Doors/Core). Sorry for the confusion!
