### ISSUE TITLE
Missing capability check causes crashes

### ISSUE THREAD

**Issue by BlayTheNinth** [LogicTechCorp/NetherEx-Archive#38]
Hi,

you need to check if the capability passed to the `getCapability` function is indeed the capability for the ItemHandler, otherwise you will cause crashes with anything requesting a capability other than an IItemHandler on your tiles. See https://github.com/blay09/RefinedRelocation2/issues/28 for example.

Relevant line of code that needs an if(capability == ...) check:
https://github.com/LogicTechCorp/NetherEx/blob/4f7bb06ba11d5fbaa017aa66b9d56a0dd81b89ee/src/main/java/nex/tileentity/TileEntityInventory.java#L91

**Comment by LogicTechCorp** [comment]
This issue has been fixed in the latest version.
