### ISSUE TITLE
Rime Ore/Gem/Blocks Lack OreDict

### ISSUE THREAD

**Issue by eriniki** [LogicTechCorp/NetherEx-Archive#39]
Running NetherEx-1.11.2-1.1.8.9 (haven't tested latest, yet), I noticed that Rime lacks oredict entries for the ore, gems, and blocks. 

Additionally, as there's also no furnace recipes for it (or for Amethyst Ore!), silk-touching the blocks gives you an effectively 'useless block' you have to place down and mine again to get Rime from. (Amethyst Ore is slightly better here, as Thermal Etc/Immersive Engineering both generate Pulverizer/Crusher recipes from the oredict entries, meaning the blocks can be turned into two Amethyst.)

As Amethyst has ore entries, and the blocks page on the wiki lists both of them as Ores, I assume it's unintentional that Rime's missing?

**Comment by LogicTechCorp** [comment]
All of these issue have been fixed in the latest version. I didn't originally add Ore Dictionary entries for the Rime Ore, Block, and Item because it is a unique ore and I didn't expect anyone else to create a similar ore.
