### ISSUE TITLE
Spinout in overworld [1.12] latest version

### ISSUE THREAD

**Issue by mansrm81** [LogicTechCorp/NetherEx-Archive#40]
I got killed by a spinout in the nether and when I respawned the spinout is in the overworld trying to get to me in my house.

**Comment by LogicTechCorp** [comment]
When you died, were you near your Nether portal? If so, then the Spinout probably came through your Nether portal.

**Comment by mansrm81** [comment]
yeah I was but not that close at least over 20 blocks, how did it path to me though is what I don't get

**Comment by LogicTechCorp** [comment]
It could possibly be another Spinout that went through the portal to the Overworld while you were in the Nether. They can track you from up to 32 blocks away.

**Comment by LogicTechCorp** [comment]
Closing as this does not appear to be a bug.
