### ISSUE TITLE
BOP nether biomes don't generate

### ISSUE THREAD

**Issue by 0Navis0** [LogicTechCorp/NetherEx-Archive#41]
BiomesOPlenty nether biomes don't generate when Nether Ex is present.

**Comment by LogicTechCorp** [comment]
For BOP compatibility, please take a look at this link: https://www.reddit.com/r/NetherEx/wiki/configuration#wiki_premade_biome_lists

**Comment by Hypsellis** [comment]
Does it take account of he rarity of the biomes ? Because Polar Chasm is highly rarer than other BOP nether biomes.

**Comment by LogicTechCorp** [comment]
@Hypsellis Yes, it does take into account the biome rarities.
