### ISSUE TITLE
Ember mob in Nether

### ISSUE THREAD

**Issue by RayzoRayy** [LogicTechCorp/NetherEx-Archive#42]
It seems that Embers are Invisible in the current 1.12 modpack I am developing. I am not sure if it's an issue/bug with this mod, or another one is causing this. I can see Embers due to the mod Neat I have installed so I see the nameplate for the mob. But the mob its self is invisible.

**Comment by LogicTechCorp** [comment]
This is not an issue, it is supposed to be invisible and it emits fire particles.

**Comment by RayzoRayy** [comment]
Thanks for letting me know.

**Comment by LogicTechCorp** [comment]
No problem.
