### ISSUE TITLE
[1.11.2/1.12]Unable to place Bedrock in the Nether while in creative

### ISSUE THREAD

**Issue by LogicTechCorp** [LogicTechCorp/NetherEx-Archive#46]
Players are unable to place Bedrock in the Nether while they are in creative.

**Comment by beesyndicate** [comment]
I also have this issue in 12.2

**Comment by darthvader45** [comment]
Same here, but in the overworld as well, can't even place it in survival.  Please fix, as I use creative frames of bedrock to outline where my buildings go before I begin construction.  This is way too annoying to ignore. @LogicTechCorp

**Comment by josephcsible** [comment]
Here's the cause: https://github.com/MineEx/NetherEx/commit/1dfcdbcf1f6069344cde125a9794b5b2def7850e#diff-12f52e15b9465cb49aac1e50423dbe4dR356

**Comment by darthvader45** [comment]
Thank goodness, now that block of code can be repaired, to make sure this doesn't happen again.

**Comment by darthvader45** [comment]
@LogicTechCorp Any chance this could be merged?  I cannot stand this problem, and yet do not want to remove this amazing mod.

**Comment by LogicTechCorp** [comment]
This has been fixed in the latest version.
