### ISSUE TITLE
compatibility with other mod nether plants

### ISSUE THREAD

**Issue by 0Navis0** [LogicTechCorp/NetherEx-Archive#48]
I link this issue here about the NetheEx plants that can't grow on Tainted Soil and/or Heat Sand. I report the same issue about all the other mods nether plants which can't grow on the 4 netherracks added by NetherEx. https://github.com/progwml6/Natura/issues/343

**Comment by LogicTechCorp** [comment]
The NetherEx plants are supposed to be placed on certain blocks and not every Nether block. The NetherEx Netherrack is in the Ore Dictionary and it is up to the other mod authors to check if a block is registered as Netherrack.
