### ISSUE TITLE
compatibility with other mods nether mobs

### ISSUE THREAD

**Issue by 0Navis0** [LogicTechCorp/NetherEx-Archive#49]
Nether mobs from Natura, Ad Inferos, Quark and PrimalCore don't spawn in the Nether when NetherEx is present.

**Comment by 0Navis0** [comment]
It would be nice you solve this issue and the problem of compatibilities with BOP biomes, because they are really annoying issues.

**Comment by LogicTechCorp** [comment]
As far as I know, the mobs not spawning is not my problem. The mod authors have to adjust their mob spawns to include all Nether biomes opposed to only the Hell biome. I am currently working on an update that includes BOP compatibility.

**Comment by 0Navis0** [comment]
The problems comes from you since everything works fine without NetherEx.

**Comment by LogicTechCorp** [comment]
Natura and Primal core mobs should be spawning in the Nether. The issue with Ad Inferos was fixed here: https://github.com/superdextor/Ad-Inferos-Mod/issues/7. I submitted an issue for the Quark Wraiths not spawning here: https://github.com/Vazkii/Quark/issues/628.

**Comment by 0Navis0** [comment]
Thanks for the answer, there are too the LightningCraft demons which seem to not spawn.

**Comment by An-Sar** [comment]
i have started to look into compatibility between NetherEX and PrimalCore, i have several nether mobs and a range of worldgen so it will be interesting to see how this goes.

**Comment by 0Navis0** [comment]
Any progress with this issue ?

**Comment by LogicTechCorp** [comment]
This has been fixed in the latest version.
