### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by ghost** [LogicTechCorp/NetherEx-Archive#5]
After the first crash I tried to load your Mod alone, the problem persists.

crashlog: http://paste.ee/p/JqW1H

**Comment by LogicTechCorp** [comment]
What versions of the Mod and Forge were you using? What other mods were installed? I tested it with Mod version: 0.2.0 and Forge version: 12.18.1.2011 and It loaded in fine.

**Comment by Cat-McCatface** [comment]
I got the same crash on startup using current versions of the mod and forge.
NetherEx_1.10.2-0.2.0
Forge: 2042
log: 
[crash log.txt](https://github.com/LogicTechCorp/NetherEx/files/391675/crash.log.txt)

**Comment by ghost** [comment]
At this time I'm using forge-1.10.2-12.18.1.2027 an Modversion 2.0. 
You can see that in the bottom of the log.
Today I've tested again alone with with different Forge versions and Version 0.2.0.
It works up to forge 2026. 
My problem is: I have tried to install a mod that requested a higher forge version. So I have to decide which of the two I should install.
regards

**Comment by LogicTechCorp** [comment]
Should be fixed as of version 1.10.2-0.2.1. @jokish63 @Cat-McCatface

**Comment by ghost** [comment]
thank you for thegood job (Problem solved - mod is in the Pack)
best regards Jokish
