### ISSUE TITLE
[1.11.2/1.12]Player spawns underneath Rime and Steel portals

### ISSUE THREAD

**Issue by Dakotaraptor** [LogicTechCorp/NetherEx-Archive#50]
So the problem I've been having is any portals lit with the Rime And Steel (including ones in shapes that would work in vanilla) will spawn me directly under them on the other side. In survival, this usually means suffocating to death inside blocks. Portals lit with the regular Flint And Steel do not have this problem. I'm using Nether Ex version 1.11.2-1.1.11.12 .

**Comment by Xogue** [comment]
Not sure if it will help or not, but only players spawn under the portal.  Other entities (or at least villagers) create a new vanilla portal a few blocks away from the rime and steel ones.

EDIT:  I did some testing:

[No vanilla portals nearby]
Enter vertical Rime Portal (Nether or Overworld)
 -- Create new vanilla portal and spawn player under it
 -- Villagers going from Nether to Overworld via Rime portal spawn below the "linked" Rime portal
 -- Villagers going from Overworld to Nether spawn new vanilla portal and spawn villager under it

** If a vanilla portal is nearby, players and villagers are spawned under it (except when villagers are going from nether to overworld as mentioned above
** If entering a vanilla portal from either direction, all rime portals regardless of distance are ignored.

Enter horizontal rime portal (Nether or Overworld)
 -- Create new vanilla portal and spawn player in it (not under as with vertical portals)
 -- Same with villagers going from nether to overworld (although one random villager ended up on the top of a tree, but I dont know how to reproduce that)
 -- Villagers going from overworld to nether seem to appear at the top of the vanilla portal (taking a bit of damage from their head being in the top obsidian block of the vanilla portal before they fall to the bottom blocks.

Not sure how much the extra info helps, but I was curious ;)
Hope it gets fixed soon. I love the idea of "organically shaped" portals

**Comment by CalaMariGold** [comment]
Is this going to be fixed? It's been a year with this item having a game breaking bug.

**Comment by LogicTechCorp** [comment]
1.11.2 is no longer supported. This issue has been fixed in later 1.12 versions.
