### ISSUE TITLE
Reducing the amount and size of added biomes.

### ISSUE THREAD

**Issue by MokahTGS** [LogicTechCorp/NetherEx-Archive#51]
Where and how would we go about reducing the size of the biomes added by this mod.  It seems like the nether is nothing but NetherEx biomes with a very small chance of seeing normal ones.  This is an issue when you have other mods that add to the nether like Dimensional Ores.

**Comment by LogicTechCorp** [comment]
You can increase the weight of the default biome in the config. It is located in the Biome Lists folder which is in the NetherEx config folder.
