### ISSUE TITLE
Fungi Forest Suggestions

### ISSUE THREAD

**Issue by 0Navis0** [LogicTechCorp/NetherEx-Archive#52]
I wanted to suggest to make spawn red and brown elder mushroom in their small form in Fungi Forest, and maybe vanilla red and brown mushrooms, for diversying this biome.

**Comment by LogicTechCorp** [comment]
This was decided against as the small Elder Mushrooms have unique behaviors, when eaten, that are worth the risk/reward for killing the Mogus to obtain them.
