### ISSUE TITLE
BOP Mycelial Netherrack Doesn't Spawn

### ISSUE THREAD

**Issue by 0Navis0** [LogicTechCorp/NetherEx-Archive#53]
It seems when NetherEx is present, mycelium netherrack from BOP which is supposed to spawn in Fungi Forest don't spawn more.

**Comment by LogicTechCorp** [comment]
This is a known issue. I am currently working on improving several aspects of the mod, including builtin BOP support. The update won't be out for quite a while but it will be worth the wait.

**Comment by 0Navis0** [comment]
NetherEx prevents tainted soild and heat sand from Natura to spawn too.

**Comment by 0Navis0** [comment]
https://github.com/progwml6/Natura/issues/397
