### ISSUE TITLE
Ember invisible 1.12.2

### ISSUE THREAD

**Issue by aidan5802** [LogicTechCorp/NetherEx-Archive#54]
![2017-09-26_17 53 57](https://user-images.githubusercontent.com/24734097/30886151-1168741a-a2e4-11e7-927d-395c26b3ddf7.png)

**Comment by LogicTechCorp** [comment]
By invisible, do you mean that the flame particles are not spawning? Because the Embers are meant to be invisible and they only emit flame particles.

**Comment by sebastianbhahn** [comment]
can confirm on 1.11.2. Ember is completely invisible when playing with particles disabled. maybe some base texture would be a good idea.

**Comment by gryttr** [comment]
Can also confirm on 1.12.2. It's particularly bad because you'll be walking along and suddenly start taking damage for no discernible reason, and the only way to escape is to temporarily set the game to peaceful to force-despawn it.

**Comment by Twingrey** [comment]
This happens in BigBang Mods 2018 modpack as well, the only way to kill such an invisible mob is with a potion or a lot of arrows. I tried to make a screenshot, but it seems even the hitbox is missing on those embers that bug into invisibility.

**Comment by LogicTechCorp** [comment]
This is intentional. If you'd like you can disable them from spawning by setting their spawn weight to 0 in the torrid wasteland biome config.
