### ISSUE TITLE
[1.12.2] [Suggestion] Add Ore Gen in NetherEx Biomes

### ISSUE THREAD

**Issue by MokahTGS** [LogicTechCorp/NetherEx-Archive#56]
Looking through the biomes added by this mod it's frustrating that ore doesn't generate or doesn't generate well in the biomes added by this mod.  It's even more frustrating when those biomes tend to be quite large, and consequently, quite useless.

If you were to add more compatibility for ores, modded ores, and modded trees it would blend better in mod packs.

**Comment by Espinoth** [comment]
Just found this out the hard way myself; after I'd added in NetherEnding ores to boot.  Had to remove the mod and LibEx from my server so my friends and I could actually find ores like Cobalt and Ardite from Tinker's Construct; and Draconium from Draconic Evolution.

**Comment by LogicTechCorp** [comment]
Mods that generate ore in the Nether should target blocks that are registered as "netherrack" in the ore dictionary for 1.12 or blocks that are tagged as "netherrack" in 1.14+.
