### ISSUE TITLE
Excess MapGenNetherBridge causing issues with Dimensional Control

### ISSUE THREAD

**Issue by Blargerist** [LogicTechCorp/NetherEx-Archive#57]
Your [ChunkGenerator](https://github.com/LogicTechCorp/NetherEx/blob/1.12.x/src/main/java/nex/world/gen/ChunkGeneratorNether.java) creates its own MapGenNetherBridge rather than using the one in its superclass, ChunkGeneratorHell, without overriding all methods which access the MapGenNetherBridge of the super. This causes Dimensional Control to freak out. This will also likely break other things in your nether, such as advancements requiring the player to enter a nether fortress.

The two main options for fixing this, would be to either switch to using the MapGenNetherBridge of the super (use an access transformer to make the field protected, rather than private), or override all other methods that access the field, which includes at atleast the isInsideStructure method, if not more.

Thanks! :D

**Comment by LogicTechCorp** [comment]
Thanks for this, I will look into the issue. I am not sure when the fix will be out as I am working a restructuring of the mod which may take some time.

**Comment by LogicTechCorp** [comment]
This has been fixed in the latest version.
