### ISSUE TITLE
[Compatibility Request] Ore Dictionary Wither Bone

### ISSUE THREAD

**Issue by An-Sar** [LogicTechCorp/NetherEx-Archive#59]
i quickly checked through the code to make sure a dictionary name wasn't already being used, and it didn't appear to be, hopefully i didn't just miss it.

Both Tinkers Construct and a mod i am working on provide versions of a wither skeleton bone and both are using a common dictionary name "boneWithered", is it possible to add this name to the NetherEX recipes?

Thank You

**Comment by LogicTechCorp** [comment]
I will put it on the to do list.

**Comment by acook** [comment]
For everyone still having this issue here is the CraftTweaker code to make them interchangeable, including being able to use them for the Necrotic modifier in Tinker's Construct:

```csharp
val nex_bone = <nex:item_bone_wither>; // NetherEx's Wither Bone
val wither_bone = <ore:boneWithered>; // used by Tinker's Construct for the Necrotic trait modifier
wither_bone.add(nex_bone);
recipes.replaceAllOccurences(nex_bone, wither_bone); // either bone will work in NetherEx's crafting table recipes now
```

I also use Quark and Immersive Engineering so I created this Crusher recipe as well:
```csharp
val nex_dust = <nex:item_dust_wither>; // black dye and bonemeal for elder mushrooms and nether wart
val quark_ash = <quark:black_ash>; // prevents mob spawns on blocks immediately above

mods.immersiveengineering.Crusher.addRecipe(nex_dust * 6, wither_bone, 3200, quark_ash * 2, 1);
```

**Comment by LogicTechCorp** [comment]
This has been added in the latest version.
