### ISSUE TITLE
Golden Bone Hammer

### ISSUE THREAD

**Issue by FeralGangrel** [LogicTechCorp/NetherEx-Archive#60]
I dropped this into the Discord, but I would believe it easier to have it be known here.  Any time I try and use the Golden bone hammer it breaks after 5 swings.  I originally thought it to be an issue with the vanilla areas of the Nether that I had played in before adding the mod.  Both a normal hammer and an unbreakable III were destroyed in ~5 swings.  Did some digging, got to a new biome same thing happened.
As a suggestion I started a new world and with the same results.  
I don't run any mods, in fact, this is the first mod Ive tried using in several years.  only the default Minecraft Forge mods are running alongside Nether Ex.

**Comment by LogicTechCorp** [comment]
I'll take a look, thanks.

**Comment by LogicTechCorp** [comment]
This has been fixed in the latest version.
