### ISSUE TITLE
[1.1.11.12] IllegalArgumentException: Cannot set property PropertyEnum ...

### ISSUE THREAD

**Issue by kreezxil** [LogicTechCorp/NetherEx-Archive#61]
My dedicated server has been crashing constantly since a couple days ago when some player did something and I do not know what they did. All of these are for you and are likely the same thing too.

https://gist.github.com/e1c53ff42bb922a9a2f1c34fc7036c1c
https://gist.github.com/936f667be66b23e893643b0ac2d027d9
https://gist.github.com/e73b7f9504a6d0f5ee4e372d05e69f33
https://gist.github.com/97f0897ebcede740b33b68d516d0e7e9
https://gist.github.com/713dbb24debc45c5506cd5aab0c233d2
https://gist.github.com/356ef59a8af6aebcf98e64daccafb173
https://gist.github.com/0fa2684bc79f42839efefab655eebfc9
https://gist.github.com/9cc295eab7d711313d14a59067aa90b1
https://gist.github.com/3a9fac92d57d4f0cf155c7d698a5093a
https://gist.github.com/e407ed6bdf8e4e109cb8dcad9f3ebca2
https://gist.github.com/623b13ee28f4b54fcbec0aebc46ee56c
https://gist.github.com/f91a68483ba1ac8d0fe920debddf7690
https://gist.github.com/4e0355ef4b668c0d8395dc161fba71c7
https://gist.github.com/de6e0f7a94146ec728abead635487067
https://gist.github.com/84dd97400b6368330f30e8b5b4abf3ce
https://gist.github.com/7f1960b10a046f9676c5d38f61e59fc0
https://gist.github.com/d1f429901592cadedc76bcd9a57d1849
https://gist.github.com/877d6f0f4e38cafbdb448356aa699a7e
https://gist.github.com/7877655f0a7a80130f78a29c9bb2108f
https://gist.github.com/f66622e03c8404338ae287241866ab78
https://gist.github.com/eef3835a5bdf69bca68ae056e7309ea9
https://gist.github.com/f0801f47240d339b252ec915cd36e4c8
https://gist.github.com/993da4289af9d788cd93aaa88117b154
https://gist.github.com/b186c4b76072c7fd6dfba59191f6eade
https://gist.github.com/b28df215d1d475ea72ad171fa03b15f9
https://gist.github.com/6fd4f26a1c5d8ab961a473b399af33ae
https://gist.github.com/52cdc3f058bf376c44926d8e84537105
https://gist.github.com/af4a1cc7a8c67f305d5fb0a7b0dc755e
https://gist.github.com/a90945902eda3a8c127afb8992f52849
https://gist.github.com/7654b75268559a25c9a2acee37be15ae

And these are their timestamps so that you can see how often it happened over the last 20 hours:
crash-2017-11-20_14.09.39-server.txt
crash-2017-11-20_14.16.25-server.txt
crash-2017-11-20_14.19.49-server.txt
crash-2017-11-20_14.41.17-server.txt
crash-2017-11-20_14.46.47-server.txt
crash-2017-11-20_14.50.53-server.txt
crash-2017-11-20_16.08.35-server.txt
crash-2017-11-20_16.33.59-server.txt
crash-2017-11-20_16.37.46-server.txt
crash-2017-11-20_16.42.12-server.txt
crash-2017-11-20_16.46.27-server.txt
crash-2017-11-20_16.49.41-server.txt
crash-2017-11-20_16.52.58-server.txt
crash-2017-11-20_16.57.28-server.txt
crash-2017-11-20_17.01.41-server.txt
crash-2017-11-20_17.12.28-server.txt
crash-2017-11-20_17.29.02-server.txt
crash-2017-11-20_17.35.12-server.txt
crash-2017-11-20_17.38.56-server.txt
crash-2017-11-20_17.43.56-server.txt
crash-2017-11-20_17.48.04-server.txt
crash-2017-11-20_17.51.05-server.txt
crash-2017-11-20_17.56.00-server.txt
crash-2017-11-20_17.59.17-server.txt
crash-2017-11-20_18.04.56-server.txt
crash-2017-11-20_19.15.48-server.txt
crash-2017-11-20_20.05.22-server.txt
crash-2017-11-20_20.08.48-server.txt
crash-2017-11-20_20.13.10-server.txt
crash-2017-11-20_20.42.42-server.txt

**Comment by LogicTechCorp** [comment]
It should be fixed in the latest version.
