### ISSUE TITLE
Tilled and Trodden blocks are dark with smooth lighting off

### ISSUE THREAD

**Issue by piber20** [LogicTechCorp/NetherEx-Archive#64]
I recently got back into Minecraft mods, so I may be a bit out of the loop. But I believe I found a problem that happens when smooth lighting is disabled, which is typically how I play the game:

Smooth Lighting on:
![smooth on](https://i.imgur.com/MdeB2pi.png?1)

Smooth Lighting off:
![smooth off](https://i.imgur.com/rjPiggO.png?1)

The tilled and trodden blocks appear much darker with smooth lighting off. I'm not a Minecraft modder, but my guess would be that they're set as full blocks, even though they actually aren't, resulting in the lighting engine making the top part of the block dark.

I believe I have the latest version, and I have confirmed that this still happens without any other mods active.

This is still one of my favorite mods, though. Keep up the good work.

**Comment by LogicTechCorp** [comment]
This has been fixed in the latest version.
