### ISSUE TITLE
[1.12.2] Custom Ores for Tinker's Contruct [Suggestion/Changes]

### ISSUE THREAD

**Issue by Draskh** [LogicTechCorp/NetherEx-Archive#66]
If Tinker's Construct is present it generates Cobalt and Ardit ores in the nether. But there are no ore variants for the new types of netherrack that are added by NetherEx. Maybe that could be changed.

**Comment by Draskh** [comment]
I would also suggest to integrate also some other ores of common mods. 
That can be solved by overlay textures of the corresponding ores that were put over the different version of netherrack added by NetherEx.

**Comment by SafsoufaS** [comment]
Does it generate as of now?

**Comment by ProsperCraft** [comment]
No, the tinkers ores do not generate in 1.12.2 either. with NetherEx-1.12.2-2.0.15

**Comment by ProsperCraft** [comment]
https://github.com/LogicTechCorp/NetherEx/issues/56

**Comment by LogicTechCorp** [comment]
Mods that generate ore in the Nether should target blocks that are registered as "netherrack" in the ore dictionary for 1.12 or blocks that are tagged as "netherrack" in 1.14+.
