### ISSUE TITLE
NetherEx prevents some other mod blocks to spawn

### ISSUE THREAD

**Issue by 0Navis0** [LogicTechCorp/NetherEx-Archive#67]
I repost this issue because it still exists. NetherEx prevents some other mod blocks to spawn, particularly BiomesOPlenty and Natura ones. The ones I noticed for the time is the mycelial netherrack, the tainted soil, and the heat sand.

**Comment by 5t0rmr1d3r** [comment]
Netherex has it's own chunk generator, to include Biomesop look at the wiki of netherex

**Comment by 0Navis0** [comment]
Already did, the biomes generates well, the problem doesn't come from it.

**Comment by HorizonsMC** [comment]
Natura ones spawn for me, even in the new biomes. Not sure about BiomesOP, I don't have it installed so maybe that is the problem.

**Comment by nicolhaq** [comment]
Mushroom and dynamic hellbark tree are not spawning when the bop dynamic tree compat mod is installed.

**Comment by LogicTechCorp** [comment]
This issue has been fixed in newer versions.
