### ISSUE TITLE
A lot of problems with modded mobs

### ISSUE THREAD

**Issue by 0Navis0** [LogicTechCorp/NetherEx-Archive#7]
From what I noticed:
- EnderZoo mobs spawn in the nether while they shouldn't
- AbyssalCraft demon pigs, cows and chickens doesn't seem to spawn
- Quark wraith doesn't seem to spawn

**Comment by LogicTechCorp** [comment]
The EnderZoo issue should be fixed as of version 1.10.2-0.3.1 
I made a pull request for AbyssalCraft that was merged and another one for Quark which has yet to be merged. @Hypsellis

**Comment by 0Navis0** [comment]
I have the feeling that NetherEx prevents the enderman to spawn in the Nether too.

**Comment by LogicTechCorp** [comment]
> I have the feeling that NetherEx prevents the enderman to spawn in the Nether too.

I completely forgot about the Enderman. Will be fixed in the next update.
