### ISSUE TITLE
NetherEX Incompatible With Biome Tweaker

### ISSUE THREAD

**Issue by HorizonsMC** [LogicTechCorp/NetherEx-Archive#70]
If using NetherEX you are unable to make changes with biome tweaker.

https://github.com/superckl/BiomeTweaker/issues/158

**Comment by Kyrinon** [comment]
You do not need to use biome tweaker. everything can be handled natively in the "nex_biome_list" config.
There is a great explanation on how to use the config  found here https://www.reddit.com/r/NetherEx/wiki/configuration
