### ISSUE TITLE
Option to disable Pigtificates villages.

### ISSUE THREAD

**Issue by nmarshall23** [LogicTechCorp/NetherEx-Archive#75]
I'm getting a FPS drop, that seems to have something to do with Pigtificates villages, and Advanced Rocketry.

Advanced Rocketry adds a lot of new dimensions, the Pigtificates villages feature is tracking possible Pigtificates villages in every dimension. I know that because Pigtificates villages is acting just like vanilla villages and adding a file to every dimension.

I not sure what triggers the FPS drop. But if I remove NetherEx it doesn't happen. Or if I limit the number of Advanced Rocketry plants, ie dimensions to 1, it also doesn't happen.

Seeing as I have never found a Pigtificates village I'd rather disable this feature then not be able to use this mod.

**Comment by LogicTechCorp** [comment]
This has been fixed in the latest version.
