### ISSUE TITLE
[1.10.2] Shift right clicking crashes to desktop

### ISSUE THREAD

**Issue by TheSomnambulist** [LogicTechCorp/NetherEx-Archive#76]
I know this is a slightly older version, but when playing with the new thaumcraft I tried to scan some stuff in the nether.  Whenever I tried the netherrack variants, I would instantly crash.  I tried without the thaumometer, and it seemed to be just clicking.  

Makes building in the nether an impossible proposition, too.

Crash logs:
https://pastebin.com/50H8X5LK

**Comment by LogicTechCorp** [comment]
The 1.10.x versions are no longer supported.
