### ISSUE TITLE
Tinker's Construct magma slimy islands doesn't generate

### ISSUE THREAD

**Issue by 0Navis0** [LogicTechCorp/NetherEx-Archive#8]
It seems that the Tinker's Construct magma islands doesn't generate them when NetherEx is present.

**Comment by LogicTechCorp** [comment]
Should be fixed as of version 1.10.2-0.3.1 @Hypsellis

**Comment by 0Navis0** [comment]
They generate them now but incorrectly often. They are sometimes merged with walls or ceiling. The trees generate them partially in walls and ceiling. It seems to be the same too for the Nether fortress. And glowstone clusters generate them sometimes in the void.

**Comment by LogicTechCorp** [comment]
The way they generate has nothing to do with NetherEx. Tinkers' Construct just checks if a lava block is surrounded, on each side, by another lava block.
