### ISSUE TITLE
Living update event tick time 

### ISSUE THREAD

**Issue by sscards55** [LogicTechCorp/NetherEx-Archive#81]
It seem that the living update event handler is using quite a bit of CPU time on the server side.
![2018-03-08_22 19 21](https://user-images.githubusercontent.com/5591207/37153410-f99e01e4-231f-11e8-90b2-9c9ba58731ba.png)
I took a quick peek at it, and I believe that the freezing effect in can be handled when the potion is added and removed from the entity rather than during an update tick. If I'm not mistaken either the events exist, or there are methods in one of the potion classes.
My second issue is, the event handler is registered on both the client and the server. I fairly certain most events could be handled on only one side.
If I'm wrong in my thinking, feel free to correct me.

**Comment by LogicTechCorp** [comment]
This has been fixed in the latest version.
