### ISSUE TITLE
MultiModel minecraft:builtin/missing is empty

### ISSUE THREAD

**Issue by naqaden** [LogicTechCorp/NetherEx-Archive#83]
I see 11 of these errors every time I load Minecraft 1.12.2, even with NetherEx as the only mod:
`[main/ERROR] [FML]: MultiModel minecraft:builtin/missing is empty (no base model or parts were provided/resolved)`

Those errors are related to the following files:
NetherEx-1.12-2.1.14.15.jar\assets\nex\blockstates\wall_vanilla.json
NetherEx-1.12-2.1.14.15.jar\assets\nex\blockstates\wall_brick_nether.json
NetherEx-1.12-2.1.14.15.jar\assets\nex\blockstates\wall_basalt.json

**Comment by LogicTechCorp** [comment]
This is not an issue. It is a side effect due to how I create my wall blocks.
