### ISSUE TITLE
usuing summon comand gives a wierd "thing"

### ISSUE THREAD

**Issue by Bullorg74** [LogicTechCorp/NetherEx-Archive#84]
Netherex : 1.12-2.1.1.4.15
Forge : 14.23.3.1668

/summon nex:passive_pigtificate_leader works just fine and I get the "big fat boss"
/summon nex:passive_pigtificate has another result. Something that looks like all the pigtificates in one. Name according to Wavla nex.entity.passivePigtificate.cheif.name and according to Horsepowers entity thing is : nex.entity.passive.EntityPigtificate.

I want to summon them to make custom villages with ruins.

(spawn eggs work as they should)

![2018-04-21_19 26 41](https://user-images.githubusercontent.com/38103415/39086996-00492dc4-459a-11e8-91d5-a4e34dd88fe5.png)

**Comment by st753m** [comment]
I was doing some experimenting and found a solution/workaround.  

This rule works:
/summon nex:passive_pigtificate ~ ~1 ~ {Career:1}

1=hunter, 2=gatherer, 3=scavenger, 4=armorsmith, 5=toolsmith, 6=enchanter, 7=brewer

It looks like if the {Career} isn't set manually it doesn't get set at all?
