### ISSUE TITLE
Re: nex_biome_list and the weight settings

### ISSUE THREAD

**Issue by Bullorg74** [LogicTechCorp/NetherEx-Archive#85]
Hi first really nice mod TY.

Now for the question:
All biomes EXEPT Fungi_forest have a "weight" setting but fungi_forest have a  "biome_weight": setting.

I'm testing diffrent values as I want to tweak the nether gen to mostly Hell and Arctic abyss but I guess I'm doing it wrong. 
A weight of 1 in my head means less of that biome than if it was 10? Wrong ?

Nether Ex : 1.12-2.1.14.15
Forge : 14.23.3.2668

**Comment by LogicTechCorp** [comment]
Try renaming "biome_weight" to "weight".

**Comment by Bullorg74** [comment]
Seems to do the trick.

TY for answering
