### ISSUE TITLE
[1.12] [Suggestion] Register wither bones in OreDict

### ISSUE THREAD

**Issue by CactusDuud** [LogicTechCorp/NetherEx-Archive#87]
Tinker's construct adds withered bones in OreDict under boneWithered, and it would be nice to be able to use the NetherEx bones for tinker's construct tools

**Comment by LogicTechCorp** [comment]
NetherEx's Wither bones are registered to the Ore Dictionary under boneWithered. Does it not work? If not, I'll have to take a look for the next release.

**Comment by CactusDuud** [comment]
Double checked and it does not work
[https://imgur.com/a/mQyEF0l](url)

**Comment by angelnc1989** [comment]
If you come around to implement this, I would appreciate the use of oredict wither bones in recipes too.

**Comment by LogicTechCorp** [comment]
This has been added in the latest version.
