### ISSUE TITLE
Urn of Sorrow: Invalid item breaks the summoning process forever!

### ISSUE THREAD

**Issue by Jamdog** [LogicTechCorp/NetherEx-Archive#89]
When summoning the Queen Ghast, if you right click the Pot of Sorrow with the wrong item, it renders it unusable for everyone.

In this case, someone clicked on it with a pineapple:
![image](https://user-images.githubusercontent.com/94101/41132101-e93504fe-6ab6-11e8-80e1-dd1fc68b5cab.png)

The pineapple is only visible for the person who placed it, and when another player tries to place a Ghast Tear, it appears to work, but the ghast tear becomes a ghost item in the inventory, and the Queen Ghast never appears.

Currently, the only solution is to break the pot in Creative mode, then put the pot back (with a setblock command).  When you break the pot, the invalid item will drop out of the pot's inventory.

One solution would be to simply throw the item back out of the pot if it's not a ghast tear...?  I believe the 4 extra lines for an 'else' case, added at line 57 of _TileEntityUrnOfSorrow.java_ might cure it.

```
            if(stack.getItem() == Items.GHAST_TEAR)
            {
                if(getSummoningTime() == 0)
                {
                    getWorld().playSound(null, getPos(), NetherExSoundEvents.ENTITY_SUMMON_GHAST_QUEEN, SoundCategory.AMBIENT, 0.5F, 1.0F);
                }
                setSummoningTime(getSummoningTime() + 1);
                setCanBreak(false);
            } else if(!stack.isEmpty()) {
              // Throw out invalid items
              spawnItemStack(getWorld(), getPos(), stack);
              getInventory().setStackInSlot(0, ItemStack.EMPTY);
            }
```

**Comment by Jamdog** [comment]
Please fix this soon!  I accidentally right-clicked on it with my sword - now I'm in the nether with no sword!  I can't get it back!  At least if it throws out invalid items, things like this won't happen to other people...
![2018-06-09_13 54 51](https://user-images.githubusercontent.com/94101/41191846-63fba95e-6bed-11e8-9347-a1998e4eefcf.png)

**Comment by LogicTechCorp** [comment]
You have to hold shift and right click the urn to remove items.

**Comment by Jamdog** [comment]
If shift-right-click is supposed to remove items from the urn, then this mechanic is broken - I tried left-click, right-click, shift-left-click and shift-right-click to remove the sword - nothing worked.  The person who accidentally placed the pineapple also tried shift-right-click.

I will test this again before re-opening the issue, but maybe a quick change to line 111 of **blocks/blockUrnOfSorrow.java** would prevent this from happening, by only allowing the player to put Ghast Tears into the urn?

```
- if(inventoryStack.isEmpty() && !player.getHeldItemMainhand().isEmpty())
+ if(inventoryStack.isEmpty() && !player.getHeldItemMainhand().isEmpty() && heldStack.getItem() == Items.GHAST_TEAR)
```

**Comment by LogicTechCorp** [comment]
I will take a look at this for the anniversary update.

**Comment by LogicTechCorp** [comment]
This has been fixed in the latest version.

**Comment by SekretOne** [comment]
Nope. Just ate a tinker's tool and the urn is completely unbreakable.

EDIT: ah wait. Make sure you don't have anything in your off hand.
