### ISSUE TITLE
suggestions for improving the mod

### ISSUE THREAD

**Issue by 0Navis0** [LogicTechCorp/NetherEx-Archive#9]
I just come to suggest some mods from wich some or all the contents could be included since these mods are dead and abandonned by their modders.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1279248-the-nether-expansion-v0-3
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294968-natura

**Comment by LogicTechCorp** [comment]
I already have permission, from the Author of Nether Expansion, to include his content in my mod. And as Natura is in the public domain, I'll see what my team decides. @Hypsellis

**Comment by 0Navis0** [comment]
Wow it's awesome about Nether Expansion. I began to despair about this mod come back. I'm impatient to see the result when you will include all the contents of this mod. It would be awesome too if the Natura content could be included in this mod too. ;)
