### ISSUE TITLE
NetherEx crashing on load with NullPointerError

### ISSUE THREAD

**Issue by qchronod** [LogicTechCorp/NetherEx-Archive#90]
I'm having a strange error with my SevTech 3.0.7 server. One of the players was in the overworld when the server crashed with this:

> // Ooh. Shiny.
> 
> Time: 6/7/18 6:33 PM
> Description: Exception ticking world
> 
> java.util.ConcurrentModificationException
> 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
> 	at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
> 	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:114)
> 	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
> 	at java.lang.Thread.run(Thread.java:748)

And upon trying to restart the server it continuously fails with the NullPointerError
https://pastebin.com/PvBjevSH  (full crash log)

I've disabled the mod and it started up fine (except for complaining about missing blocks and broken recipes and whatnot), then if I re-enable to mod again it causes the same crash as before. Also tried starting the server with the entire world removed (in case it was a corrupted chunk) and it still crashed.

I'm kind of at a loss for what else to do in order to get the server to run again.

**Comment by LogicTechCorp** [comment]
This appears to be an issue with loading the biome config. Did you make any changes to the config? Try deleting the biome config and restarting the server.

**Comment by qchronod** [comment]
I had made no changes to any of the files between the time it ran fine and when it would consistently crash. 

Anyway I've updated the server to 3.0.8 and it magically started working again. I can only assume that the config file got corrupted somehow and the update replaced it with a working one.
