### ISSUE TITLE
Exception loading blue fire

### ISSUE THREAD

**Issue by JonathanPlovie** [LogicTechCorp/NetherEx-Archive#92]
Hello

During the assembling & testing of my modpack I run into this error. It doesn't load the blue fire added by this mod, nor can I find it in the mod (opened with 7Zip and tried to find it)

Error starts at 552 I believe. Doesn't crash modpack, but it bothers me.
Running Forge 14.23.4.2705
Netherex 1.14.15

[latest.log](https://github.com/MineEx/NetherEx/files/2086786/latest.log)

**Comment by LogicTechCorp** [comment]
That's just an error because it tries to load the fire's item model. The fire still loads and functions as expected, you don't need to worry about this.
