### ISSUE TITLE
Food oredictionary

### ISSUE THREAD

**Issue by angelnc1989** [LogicTechCorp/NetherEx-Archive#98]
I would nice to have the food items added to appropriate oredictionary entries.

Raw Ghast Meat: listAllmeatraw, listAllghastraw, foodMeats
Cooked Ghast Meat: listAllmeatcooked, listAllghastcooked, foodMeats
Congealed Magma Cream: foodCongealedmagmacream
Enoki Mushroom: listAllmushroom, mushroomAny, cropEnokimushroom, listAllveggie

**Comment by LogicTechCorp** [comment]
This has been added in the latest version.
