### ISSUE TITLE
[Compat] Move entity registry to preInit

### ISSUE THREAD

**Issue by drakray** [LogicTechCorp/NetherEx-Archive#99]
Could it be possible to move NetherExEntities.init(); to preInit please, that would allow CraftTweaker to be able to "see" entity for their command like .addDrop()

Thanks :)

**Comment by LogicTechCorp** [comment]
I couldn't see why not. Unless there are issues with it, I'll be sure to
include it in the next release.

**Comment by LogicTechCorp** [comment]
This has been done in the latest version.
